### ISSUE TITLE
About reserved filenames for Windows

### ISSUE THREAD

**Issue by streetycat** [buckyos/CYFS#106]
err: (IoError, create dir for object blob error! path=C:\\cyfs\\data\\named-object-cache\\objects\\con/mm6, could not create directory path `C:\\cyfs\\data\\named-object-cache\\objects\\con/mm6`, None)"

The error will happen frequently for windows, the 'con' is reserved for Windows, It should be mapped to other.

**Comment by lurenpluto** [comment]
There were omissions in the previous repair commits, which has been corrected and the corresponding test cases have been added

bb596b858548a7b32a3cb9ee2b1988f4144a2397
