### ISSUE TITLE
AppManager incorrectly enters the UninstallFailed state when uninstalling DecApp

### ISSUE THREAD

**Issue by weiqiushi** [buckyos/CYFS#156]
When AppManager uninstalls DecApp, if the DecApp service folder is occupied, AppManager will mark it as UninstallFailed status. Should it be marked as successfully uninstalled here? If the occupied folder may cause the installation to fail in the future. Should it go to InstallFailed at the time of installation, or should it remain UninstallFailed?

**Comment by lurenpluto** [comment]
When uninstalling an app, how do we define uninstallation failure? Based on my understanding, uninstalling an app generally involves the following core steps:

- System state: Currently, there should be a set of app-related data associated with the root state. If this data is deleted or the state is modified, the app should be considered uninstalled (at least from a system perspective).

- Local installation files: Executable files, scripts, and the www directory, etc.

So, the key question is, how do we define uninstallation failure? Should both of the above steps be successful for the uninstallation to be considered successful? Or, as long as the system state in the first step is successfully uninstalled, it is considered successful?

Looking at the uninstallation of apps on the Windows platform, it is quite common for some data to remain. However, in most cases, this does not affect the successful uninstallation of the app.

**Comment by weiqiushi** [comment]
I think we can make a decision in the installation logic of DecApp: if the installation directory cannot be cleared during installation, then the installation is judged as failed.

Then, when uninstalling, we only need to make sure that the system state is cleared correctly, and the uninstallation can be regarded as successful. At this time, there are some local files left, and it does not affect the judgment of whether the uninstallation is successful or not.

Translated with www.DeepL.com/Translator (free version)

**Comment by weiqiushi** [comment]
finish at f010265d

**Comment by lizhihongTest** [comment]
When uninstalling  DEC APP, is the app data of DEC APP being deleted? Or has there been consideration for providing a way for users to choose whether or not to clear the data of DEC APP during uninstallation? If the data of DEC APP is not cleaned up, then the disk space occupied by DEC APP will never be released.

**Comment by weiqiushi** [comment]
No. DecApp's data, including root_state and the separate app data folder, are not deleted. The current design does. It may be considered in the future to provide the option of whether to delete data when uninstalling DecApp.
