### ISSUE TITLE
AppManager's install command timeout may cause the child install process to not be killed

### ISSUE THREAD

**Issue by weiqiushi** [buckyos/CYFS#157]
AppManager has a timeout of 15 minutes for each installation command when executing DecApp's installation command. When the time is exceeded and the installation command has not exited, child.kill() will be called to kill it.

Under windows system, if the install command starts a child process, such as `npm i`, child.kill() may not kill its child process, which may lead to problems such as the DecApp folder being occupied.

**Comment by weiqiushi** [comment]
May be related to issue #156

**Comment by lurenpluto** [comment]
When AppManager invokes some external "uncontrollable" processes to execute commands, there are certain risks involved:

These command processes may spawn multiple child processes.
Some operations of these processes might get stuck due to various environmental factors, such as network issues, etc.

Therefore, this raises requirements for AppManager's monitoring and handling of these command processes, taking into account these possible situations, and implementing timeout and retry mechanisms.

To terminate a process and all its child processes on Windows, you could consider the following approach:

- Use taskkill /F /T /PID <ProcessID>

Internally, this command should use Windows API's process enumeration APIs to find all processes with the target process as their parent (including the entire process tree). Alternatively, you can call the native API in Rust to achieve the same result.

- For more advanced control, you can consider managing these "uncontrollable processes" using Jobs. Based on the granularity of Jobs, you can perform complex operations like killing all processes within the job.

**Comment by weiqiushi** [comment]
Use taskkill to control install process on Windows may be a better solution.

**Comment by weiqiushi** [comment]
finish at edba014c: use taskkill /F /T /PID {pid} to stop install command when it timeout on windows

**Comment by lizhihongTest** [comment]
@weiqiushi  I have tested it, and during the DEC APP installation process, if it runs for more than 15 minutes, The windows app-manager can correctly kill the DEC APP installation process.The linux app-manager cann`t correctly kill the DEC APP installation process.App-manager did not change the status of the DEC APP to InstalledFailed, continued to execute dec app start.

## Test Env
OOD Service : 1.1.0.746-nightly (23-04-10)
OOD System : Linux/Windows

## Test data
code: https://github.com/lizhihongTest/cyfs-dec-app-test/tree/main/nighlty_src/dec-app-install-timeout
dec app: cyfs://5r4MYfFJ7ktzBzSi1sWmU7BJLgpEEdp8ukbWemsFuQc1/9tGpLNnSN39JEAfMzKs1GFCe5GsPhbRXt49fCnL84A6g

## Test code
Set the code of dec app install to run for 16 minutes, exceeding the maximum time limit of dec app install installation by 15 minutes

Expect result : "npm i && node service/service.js --install" will run 15 min be killed, the log just consile "dec app is installing 14 min"

If app-manager not kill install  preocess, the log will consile "dec app is installing 15 min"

``` https://github.com/lizhihongTest/cyfs-dec-app-test/blob/main/nighlty_src/dec-app-install-timeout/service/service.js
"use strict";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const check_cmd_1 = require("./check_cmd");
const DEC_ID = "9tGpLNnSN39JEAfMzKs1GFCe5GsPhbRXt49fCnL84A6g";
const cyfs = require('cyfs-sdk');
//  This is the entry point of the service
async function main() {
	cyfs.clog.enable_file_log({
        name: DEC_ID,
        dir: cyfs.get_app_log_dir(DEC_ID),
    });
    // Use check_cmd_and_exec to ensure the process provides the correct running mutex and App Manager required functionality. 
	// It is recommended to use the string of DECId for this name to avoid conflict with other App processes
    let install = check_cmd_1.check_cmd_and_exec(DEC_ID);
    if (install) {
        // If running 'node service.js --install', the install returned by check_cmd_and_exec will be true. 
		// Here, some initialization work is usually done for the first installation or after upgrading.
		let install_time = 16;
		while(install_time>=0){
			console.info(`dec app is installing ${install_time - 16} min ,wait 60s.`)
			await cyfs.sleep(60*1000);
			install_time = install_time - 1;
		}
		console.info(`dec app install finished!`)
		// At this stage, check_cmd_and_exec will not maintain and check the process lock, and the process needs to exit actively after initialization.
		
        process.exit(0);
    }
    
	// If running 'node service.js --start', or without any parameter, install will be false, and the normal startup process will be followed.
	// The 'open_default' here has no actual function, it just allows the service process to continue running. Otherwise, the service process will keep exiting, which will be judged as a running failure by the app-manager.

    let stack = cyfs.SharedCyfsStack.open_default()
    await stack.online();
}
main();

```

## Test Result

### Linux OOD run dec app run with docker
The dec app install preocess was killed after running for 15 minutes. However, the app-manager did not change the status of the DEC APP to InstalledFailed, but continued to execute dec app start.
<details>
Line 1663: [2023-04-11 17:00:59.844417 +08:00] INFO [ThreadId(6)] [service/app-manager/src/non_helper.rs:406] register app name success, app:9tGpLNnSN39JEAfMzKs1GFCe5GsPhbRXt49fCnL84A6g, name:dec-app-install-timeout
Line 1664: [2023-04-11 17:00:59.844450 +08:00] INFO [ThreadId(6)] [service/app-manager/src/app_install_detail.rs:65] save install detail, 9tGpLNnSN39JEAfMzKs1GFCe5GsPhbRXt49fCnL84A6g, Some("1.0.3")
Line 1665: [2023-04-11 17:00:59.844493 +08:00] INFO [ThreadId(6)] [service/app-manager/src/app_cmd_executor.rs:651] next cmd is Start, will change app:9tGpLNnSN39JEAfMzKs1GFCe5GsPhbRXt49fCnL84A6g to status: Starting
Line 1666: [2023-04-11 17:00:59.844502 +08:00] INFO [ThreadId(6)] [service/app-manager/src/app_cmd_executor.rs:573] after execute cmd [Install(InstallApp { ver: "1.0.3", run_after_install: true })], change app from [Installing] to [Starting], app:9tGpLNnSN39JEAfMzKs1GFCe5GsPhbRXt49fCnL84A6g	
</details>

### Windows OOD run without docker

The dec app was killed after running for 15 minutes
<details>
[info],[2023-04-11 16:13:37.778],<>,dec app is installing 0 min ,wait 60s., service.js:20
[info],[2023-04-11 16:13:37.780],<>,open log file success: file=C:\cyfs\log\app\9tGpLNnSN39JEAfMzKs1GFCe5GsPhbRXt49fCnL84A6g//9tGpLNnSN39JEAfMzKs1GFCe5GsPhbRXt49fCnL84A6g.0.log, index.js:94817
[info],[2023-04-11 16:14:37.790],<>,dec app is installing -1 min ,wait 60s., service.js:20
[info],[2023-04-11 16:15:37.804],<>,dec app is installing -2 min ,wait 60s., service.js:20
[info],[2023-04-11 16:16:37.812],<>,dec app is installing -3 min ,wait 60s., service.js:20
[info],[2023-04-11 16:17:37.828],<>,dec app is installing -4 min ,wait 60s., service.js:20
[info],[2023-04-11 16:18:37.832],<>,dec app is installing -5 min ,wait 60s., service.js:20
[info],[2023-04-11 16:19:37.842],<>,dec app is installing -6 min ,wait 60s., service.js:20
[info],[2023-04-11 16:20:37.848],<>,dec app is installing -7 min ,wait 60s., service.js:20
[info],[2023-04-11 16:21:37.851],<>,dec app is installing -8 min ,wait 60s., service.js:20
[info],[2023-04-11 16:22:37.865],<>,dec app is installing -9 min ,wait 60s., service.js:20
[info],[2023-04-11 16:23:37.869],<>,dec app is installing -10 min ,wait 60s., service.js:20
[info],[2023-04-11 16:24:37.873],<>,dec app is installing -11 min ,wait 60s., service.js:20
[info],[2023-04-11 16:25:37.878],<>,dec app is installing -12 min ,wait 60s., service.js:20
[info],[2023-04-11 16:26:37.882],<>,dec app is installing -13 min ,wait 60s., service.js:20
[info],[2023-04-11 16:27:37.896],<>,dec app is installing -14 min ,wait 60s., service.js:20
</details>


[dec_app_install_timout.zip](https://github.com/buckyos/CYFS/files/11198768/dec_app_install_timout.zip)

**Comment by lizhihongTest** [comment]
@weiqiushi In  Linux OOD, the app-manager install  DEC APP timesout , it still continues to execute dec app start. This issue should be fixed.

**Comment by weiqiushi** [comment]
You can create a separate Issue to describe this issue, as it will be seen as a new issue introduced by the new code

More detailed information is needed on:
1. under linux, when the install command times out, does the corresponding docker container get stopped
2. under windows, if the process started by install command starts a child process, will the child process be killed?
3. whether the installFailed state will be correctly entered if the install timeout occurs under windows

@lizhihongTest

**Comment by lizhihongTest** [comment]
The new issuse is commit in #198

**Comment by lizhihongTest** [comment]
@weiqiush The issue i under linux, when the install command times out, does the corresponding docker container get stopped

App-manager did not stop the install container. By checking the running status of docker, it was found that the install and start containers existed at the same time.
```
ubuntu@VM-24-15-ubuntu:/cyfs/log/app-manager$ sudo docker ps 
CONTAINER ID   IMAGE                     COMMAND                  CREATED          STATUS          PORTS     NAMES
83a9a1e5dc54   buckyos/dec-app-base:v1   "/bin/bash /opt/star…"   2 seconds ago    Up 1 second               decapp-9tgplnnsn39jeafmzks1gfce5gsphbrxt49fcnl84a6g
c1958f24d155   buckyos/dec-app-base:v1   "/bin/bash /opt/star…"   15 minutes ago   Up 15 minutes             decapp-9tgplnnsn39jeafmzks1gfce5gsphbrxt49fcnl84a6g-install
514db091dd60   buckyos/dec-app-base:v1   "/bin/bash /opt/star…"   22 hours ago     Up 22 hours               decapp-9tgplnnwtn7n7a4qahmvjrfbksearezhnl4b15ky2opm

```

**Comment by lizhihongTest** [comment]
The issue 2 and issue 3, I need to update my code to test again, the previous service install did not start the child process.
https://github.com/lizhihongTest/cyfs-dec-app-test/tree/main/nighlty_src/dec-app-install-timeout
+ service.js
```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const check_cmd_1 = require("./check_cmd");
const DEC_ID = "9tGpLNnSN39JEAfMzKs1GFCe5GsPhbRXt49fCnL84A6g";
const cyfs = require('cyfs-sdk');
const path = require('path');
const ChildProcess = require('child_process');
//  This is the entry point of the service
async function main() {
	cyfs.clog.enable_file_log({
        name: DEC_ID,
        dir: cyfs.get_app_log_dir(DEC_ID),
    });
    // Use check_cmd_and_exec to ensure the process provides the correct running mutex and App Manager required functionality. 
	// It is recommended to use the string of DECId for this name to avoid conflict with other App processes
    let install = check_cmd_1.check_cmd_and_exec(DEC_ID);
    if (install) {
        // If running 'node service.js --install', the install returned by check_cmd_and_exec will be true. 
		// Here, some initialization work is usually done for the first installation or after upgrading.
		let run = new Promise(async(resolve)=>{
			let  child_process = ChildProcess.exec(`node ${path.join(__dirname,"wait_min_process.js")}`)
			child_process.unref();
			child_process.on('data', (data) => {
				console.info(` wait_min_process.js console : ${data}`)
			});
			child_process.on('exit', (code, singal) => {
				console.info(` wait_min_process.js exit`);
				resolve("run finshed") 
			});
		})
		await run;
        process.exit(0);
    }
    
	// If running 'node service.js --start', or without any parameter, install will be false, and the normal startup process will be followed.
	// The 'open_default' here has no actual function, it just allows the service process to continue running. Otherwise, the service process will keep exiting, which will be judged as a running failure by the app-manager.

    let stack = cyfs.SharedCyfsStack.open_default()
    await stack.online();
}
main();
```
+ wait_min_process.js
``` js
const cyfs = require('cyfs-sdk');
async function main() {
    let install_time = 20;
    while(install_time>=0){
    	console.info(`dec app is installing ${install_time - 20} min ,wait 60s.`)
    	await cyfs.sleep(60*1000);
    	install_time = install_time - 1;
    }
    console.info(`dec app install finished!`)
    process.exit(0);
}
main();
```

**Comment by lizhihongTest** [comment]
@weiqiushi  Under the windows system, app-manager can correctly close the install process and its child processes, and can correctly modify the status of the DEC APP to InstallFailed.

**Comment by weiqiushi** [comment]
> @weiqiush The issue i under linux, when the install command times out, does the corresponding docker container get stopped
> 
> App-manager did not stop the install container. By checking the running status of docker, it was found that the install and start containers existed at the same time.
> 
> ```
> ubuntu@VM-24-15-ubuntu:/cyfs/log/app-manager$ sudo docker ps 
> CONTAINER ID   IMAGE                     COMMAND                  CREATED          STATUS          PORTS     NAMES
> 83a9a1e5dc54   buckyos/dec-app-base:v1   "/bin/bash /opt/star…"   2 seconds ago    Up 1 second               decapp-9tgplnnsn39jeafmzks1gfce5gsphbrxt49fcnl84a6g
> c1958f24d155   buckyos/dec-app-base:v1   "/bin/bash /opt/star…"   15 minutes ago   Up 15 minutes             decapp-9tgplnnsn39jeafmzks1gfce5gsphbrxt49fcnl84a6g-install
> 514db091dd60   buckyos/dec-app-base:v1   "/bin/bash /opt/star…"   22 hours ago     Up 22 hours               decapp-9tgplnnwtn7n7a4qahmvjrfbksearezhnl4b15ky2opm
> ```

@lizhihongTest OK , about the problem of docker installation container under linux is not be closed, you can create another separate issue to track it. This problem is not fixed in this milestone

**Comment by lizhihongTest** [comment]
The issue ##157 is fixed. Issues with linux docker are tracked issue  #203
