### ISSUE TITLE
chunk-manager not check disk chunk_cache correctness

### ISSUE THREAD

**Issue by lizhihongTest** [buckyos/CYFS#158]
**Describe the bug**
If I modify a chunk file in  /cyfs/data/chunk-cache  , thenI get the chunk by stack.ndn_service().get_data(), chunk-manager not check the correctness of the file hash in the disk

**To Reproduce**
1. Modify a chunk file in /cyfs/data/chunk-cache
2. Get the chunk through stack.ndn_service().get_data()
3. 
**Expected behavior**
1. The chunk-manager should check the correctness of the chunk, because the chunk content does not match the chunk_id, get_data should return an error
2. The chunk_id is calculated through the hash of the full text of the chunk content, and inconsistencies should be prohibited

**System information**
Linux/Windows

**Comment by lurenpluto** [comment]
If chunk hash mentioned in #204  detection is introduced on top of this, it would be a good mechanism for chunk-manager managed chunks and should solve the problem
