### ISSUE TITLE
App-manager local store mode does not turn off dec_app automatic update

### ISSUE THREAD

**Issue by lizhihongTest** [buckyos/CYFS#165]
**Describe the bug**
App-manager local store mode does not turn off dec_app automatic update

**To Reproduce**
1. App-manager configures local store mode
2. In local store mode, update one of the dec_app
(1) cyfs deploy publishes dec_app
(2) app-manager checks the latest dec_app version on the chain
3. App-manage gets the latest dec_app version from the chain every half hour, and then triggers an update

**Expected behavior**
Suggestion 1: dec_app update failed, you should restore the old version dec_app
Suggestion 2: In local store mode, it is recommended to turn off the automatic update trigger, because the local store mode can only update dec_app by manually executing commands. Trigger automatic update Since there is no latest version of the installation package locally, the installation will definitely fail
**System information**
cyfs-sdk 0.6.2
OOD Service ：linux 1.1.1.80

**Comment by weiqiushi** [comment]
About Suggestion 1:
More accurate state recovery: it is not possible with the current state machine of AppManager. This requires refactoring the state machine management logic of AppManager. We will probably cover this topic in one of the future Issues or discussions

@lizhihongTest

**Comment by weiqiushi** [comment]
In local repo mode, AppManager will read the app list from a local location instead of getting the latest version from the chain. At this time we can control the automatic update logic of DecApp through the local AppList

**Comment by lizhihongTest** [comment]
I created a custom app_repo to use the Local Store mode by following the steps below. Is there any other way to use the Local Store mode without using the chain? 

And when I used it, I found that using a custom app_repo, if the app list corresponding to the app_repo on the chain is changed, app-manager will synchronize the latest app list to the local

The following are the steps I took during my testing:

+ Use cyfs desc to create a device, and modify ood.desc/ood.sec to app_repo.desc/app_repo.sec

+ Use app-tool to create the app list corresponding to this repo
```
app-tool.exe list create -o app_repo -t app -u
```
+ Store app_list information to app_repo
```
+ app-tool.exe list update -c app-config.cfg -o app_repo --clear 9tGpLNnFf2xDL2TxhGh5XCNvE1ume8E7RKFijqVTLqWg
```
``` cfg
[{"id":"9tGpLNnictgciVGsrtcnR3UgQ3h66hueV9QtQhkspGPy","ver":"1.0.2","status":1},
{"id":"9tGpLNngXQbEePgnuizTGoshmGkBowjmGcG54TEJBCyM","ver":"1.0.3","status":1},
{"id":"9tGpLNnUXCvJVTn6fev1meq7WraqkH8wHLR5KRgWghPV","ver":"1.0.1","status":1},
{"id":"9tGpLNnQnEzYwvioj9FGbmmpFJy15wxQmBsDBxWbwiKX","ver":"1.0.0","status":1},
{"id":"9tGpLNni9AYycMDC9LrAAKoPqQc7VQSnodotFWXuh5D1","ver":"1.0.5","status":1}]
```

+ Replace /cyfs/etc/desc/app_repo.desc with a custom app_repo.desc

+ ood-daemon pulls the latest app list from custom app_repo
```
ood-daemon  --sync-app-repo
```

**Comment by weiqiushi** [comment]
app-manager will stop check any app update when in local repo mode. commit at 2b07945

**Comment by lizhihongTest** [comment]
Version 1.1.0.746-nightly (23-04-10)  verify that the Local Store mode will not trigger the DEC APP update
