### ISSUE TITLE
The ip may change request will fail, need to manually restart the gateway process

### ISSUE THREAD

**Issue by Revelee-art** [buckyos/CYFS#167]
**Describe the bug**
When ip changes accidentally, but you may not know that you have to restart the gateway process to restore normal access

**To Reproduce**
My CYFS browser is not accessible
**Expected behavior**
Join the automatic restart mechanism when it is not accessible

**System information**
linux ：Ubuntu 22.04
ood： nightly 1.1.0.740
runtime：This service was compiled on March 25,2023

**Additional context**

**Comment by lurenpluto** [comment]
This bug is related to the one mentioned in the issue below, and it is still in the discussion stage
#151 

Any comments and suggestions are welcome^^
