### ISSUE TITLE
App-manager local store mode update dec_app  failed

### ISSUE THREAD

**Issue by lizhihongTest** [buckyos/CYFS#168]
**Describe the bug**
App-manager local store mode update dec_app  failed

**To Reproduce**
+ My OOD Service config App-manager local store mode 
+ Installed dec_app version 1.0.3 by local store mode 
+ I want to update my dec_app to version 1.0.4，excute command cyfs deploy and check dec_app is update in meta chain
+ Excute ood-installer --sync-app-repo ，sync the latest dec_app 1.0.4  to the local successfully
+ But the App-manager auto update dec_app to 1.0.4 failed

**Expected behavior**
I can run command ood-installer --sync-app-repo success , and the App-manager can update the  dec_app success

**System information**
cyfs-sdk 0.6.2
OOD Service ：linux 1.1.1.80

**Comment by weiqiushi** [comment]
Related to Issue #165. 
if the App information is not fetched from the meta chain in local store mode, but read from a local source, the App Manager will not fetch the new version until it is synchronized using sync-app-repo. 
When AppManager can fetch the new version, it means the local repo has been synced successfully. The upgrade should also be successful at this time.

**Comment by weiqiushi** [comment]
One possible solution:
As a prerequisite, the local store model is provided for use in certain scenarios that require large-scale deployment of OOD. In this scenario, there will be an administrator to manage the DecApp version and installation in a unified way. Users are usually restricted to install DecApp by themselves.

In such a scenario, the following modifications can be made:

1. in the --sync-app-repo function of the ood-installer, in addition to synchronizing the DecApp data locally, the current version of these DecApps will also be written locally as a configuration file
2. In the local store mode of AppManager, this local configuration file will be read without getting the latest version of DecApp from the chain

In this way, an administrator can control whether the version of these DecApps is upgraded by controlling when to execute --sync-app-repo


Alternatively, when allowing users to install their own apps:
Provide another function that allows an administrator to download the data of a specified App and version locally in advance

When the user wants to install the App by himself, he needs to contact the administrator first, and let the administrator download the specified App data to the local area first, and then the user can install this App.

In the coming week, I will try to do an implementation with the above solution

**Comment by weiqiushi** [comment]
ood-installer: 
--sync-app-repo: When sync app repo, also read the value of the include app field in app-manager.toml and add it to the generated local app list object
--download-app {appid}:{ver}: Manually download the specified App and version files to the app_repo folder

app-manager:
read system app list from local app_repo folder, instead of read it from meta chain
stop check any app update when in local repo mode

**Comment by lizhihongTest** [comment]
How to configure the include app of app-manager.toml, it is recommended to provide documentation, although I can read the code to learn to use, but this is not a friendly way

**Comment by lizhihongTest** [comment]
@weiqiushi  After I execute ood-installer --sync-app-repo to synchronize the latest version of DEC APP, the process will be occupied when I install the latest version of DEC APP in the CYFS Browser. It seems that the old process has not been closed.

+ It is normal when the non-running DEC APP is updated
+ This problem occurs when the running DEC APP is updated

The following DEC APPs were included in the test:

+ 9tGpLNnWTn7N7A4qAHmvjRFbkSEaREzHNL4b15Ky2opm update failed
+ 9tGpLNndR5tyui8DkYBpEz8mFHzjfqkCVmsFusa5roHd update success
+ 9tGpLNnGEsGLkV3o2HT2XxRjikw2epbLfQNVMQa8R5qw update failed
+ 9tGpLNnUxFFXh3XxzZrJJ6UuekyzF7LJ7t7ZTtJjsPMH update failed
+ 9tGpLNnQAW5NG5NPbpP7zvUuLafPYoVU2wVcZ4xe4ecW update failed

```
[2023-04-12 15:34:56.627139 +08:00] INFO [ThreadId(20)] [service\app-manager\src\package.rs:81] install app 9tGpLNnWTn7N7A4qAHmvjRFbkSEaREzHNL4b15Ky2opm from local path C:\cyfs\app_repo\7jMmeXZZc3qPDGSjRXt9dA51Py8fBxsPS37YijTUWygk
[2023-04-12 15:34:56.627657 +08:00] ERROR [ThreadId(20)] [service\app-manager\src\app_controller.rs:154] install app:9tGpLNnWTn7N7A4qAHmvjRFbkSEaREzHNL4b15Ky2opm failed, err: (UnknownIOError, io_error: 另一个程序正在使用此文件，进程无法访问。 (os error 32), Some(IoError(Os { code: 32, kind: Uncategorized, message: "另一个程序正在使用此文件，进程无法访问。" })))
```
[lcoal_store.zip](https://github.com/buckyos/CYFS/files/11208583/lcoal_store.zip)

**Comment by weiqiushi** [comment]
> How to configure the include app of app-manager.toml, it is recommended to provide documentation, although I can read the code to learn to use, but this is not a friendly way

The logic of influencing the behavior of AppManager through app-manager.toml has not been fully determined. Therefore, the official guidance documentation is not available yet

**Comment by weiqiushi** [comment]
Several reasons for App installation failure were analyzed from the logs:
- 9tGpLNnWTn7N7A4qAHmvjRFbkSEaREzHNL4b15Ky2opm.
	In the pre-installation uninstallation logic, the node service/service.js --status command is used to check if the DecApp Service process is running. The command returns 0, which means the process is not running
	
	Therefore, AppManager judges that the uninstallation is successful, but in the installation logic, the installation fails because the directory where DecApp Service is located is occupied
- 9tGpLNnGEsGLkV3o2HT2XxRjikw2epbLfQNVMQa8R5qw and 9tGpLNnUxFFXh3XxzZrJJ6UuekyzF7LJ7t7ZTtJjsPMH
	The installation failed because there is no directory corresponding to DirId in the local app_repo directory. Is it possible that the synchronized version and the installed version do not match?
	This needs further determination
- 9tGpLNnQAW5NG5NPbpP7zvUuLafPYoVU2wVcZ4xe4ecW
	This is an identified bug, caused by the fix in Issue #156
	
	In this fix, moving the local directory deletion determination to the Install process causes an empty directory to be created if a specific directory does not exist. If there is no Service in this DecApp, an empty Service directory will be created. The subsequent operation of Install will be based on whether the service directory exists and whether the App has Service, which will be judged wrongly and cause the App without Service to fail to install.
	
	Fix: In the process of Install, just try to delete the existing directory and not to create an empty directory.

The check_cmd component in dec-app-demo is only a sample component and does not guarantee the reliability. The developer can't rely on this component completely to do the survival judgment.

**Comment by lizhihongTest** [comment]
@weiqiushi By configuring app-manager.toml app.include to use Local Store mode, the following problems may occur. app-manager.toml app.include will only be loaded once when app-manager starts, so step 1: modify app-manager.toml and step 3 ood-install --sync-app-repo need to restart app-manager to take effect .Need you to confirm that the design is so, or need to be optimized?
+  step1: config app-manager.toml  app.include
```toml
[app]
include = ["9tGpLNnPAtaYRNwPFKFsidrbtCXZWEahqyXjgzbQMHs5","9tGpLNnLsGvu3f6996V9LTV8e93faZ4JVXkqdZwxVG7Y"]
exclude = []
source = "all" 
```
+ step2: restart app-manager process, app-manager load config sucess
+ step3: ood-install --sync-app-repo ,download 9tGpLNnPAtaYRNwPFKFsidrbtCXZWEahqyXjgzbQMHs5 and 9tGpLNnLsGvu3f6996V9LTV8e93faZ4JVXkqdZwxVG7Y
+  step4: Open CYFS Browser DecApp find 9tGpLNnPAtaYRNwPFKFsidrbtCXZWEahqyXjgzbQMHs5 and 9tGpLNnLsGvu3f6996V9LTV8e93faZ4JVXkqdZwxVG7Y is not installed.
+ step5: restart app-manager
+ step6: Open CYFS Browser DecApp find 9tGpLNnPAtaYRNwPFKFsidrbtCXZWEahqyXjgzbQMHs5 and 9tGpLNnLsGvu3f6996V9LTV8e93faZ4JVXkqdZwxVG7Y is Running.

**Comment by weiqiushi** [comment]
Yes, this is the correct logic:

In local repo mode, since AppManager can only install apps from within the local path, it does not read the include field of the configuration file, but only reads the local app list file. This read logic is the same as the non-local repo mode reads the app list from the meta chain and re-reads it every half hour.

In your above operation, waiting half an hour after setp4, you can also observe that a new app is installed

**Comment by lizhihongTest** [comment]
The issue #168 has been verified in  1.1.0.748-nightly (23-04-13)
