### ISSUE TITLE
Performance optimization for A-link

### ISSUE THREAD

**Issue by lurenpluto** [buckyos/CYFS#179]
Currently, based on some feedback, there are certain performance issues when opening A-links in the cyfs-browser, especially when opening a webpage containing many embedded elements, each requesting resources via A-links. In this scenario, the entire webpage loads slowly, and the current caching mechanism for O-links does not significantly improve A-link performance.

- For the internal steps of cyfs-runtime opening an A-link, see [#162](https://github.com/buckyos/CYFS/issues/162#issuecomment-1498525423)

- For some performance diagnostic logs and analysis of A-links,  see #162

So refer to the previously provided logs and analysis, it is worth considering a cache-based optimization for the first step of A-links.

**Comment by lurenpluto** [comment]
# From the design of the "a" link protocol, introduce the corresponding caching mechanism.

From a design perspective, the "a" link supports the following three formats:

```cyfs
cyfs://a/{dec-id}/{inner-path}
cyfs://a/{dec-id}/{dir-id}/{inner-path}
cyfs://a/{dec-id}/{x.y.z}/{inner-path}
```

The key here is determining the web dir-id corresponding to the target dec-id. For the three formats above, the dir-id's search logic is as follows:

- cyfs://a/{dec-id}/{inner-path}
Find the web dir-id for the current version of the dec-id. This requires querying from OOD for the current version's dir-id.

- cyfs://a/{dec-id}/{dir-id}/{inner-path}
Specifies the target dir-id for the dec-id explicitly, which can specify a historical version (if the specified historical version dir-id still exists).

- cyfs://a/{dec-id}/{x.y.z}/{inner-path}
Specifies the target dir-id using semantic versioning, requiring a query to OOD for the dir-id corresponding to {x.y.z}.

As can be seen from the above three formats, 1 and 3 require queries to the OOD, presenting an opportunity for optimization.

## 1. Cache the current version's dir-id
This generally changes when the dec is upgraded, uninstalled, or reinstalled, and the corresponding dir-id changes. Consider using a time-based cache, such as 10 minutes.
## 2. Cache different semantic version's dir-ids
In dec app development specifications, if the web directory changes and is republished, the corresponding version needs to be updated (at least the patch version needs to be incremented). Based on this premise, the (version + dir-id) caching strategy can be designed for a relatively longer time or can be consistent with the caching strategy in 1 above.

# Two issues need to be considered also:

- If the cyfs-runtime accesses a dec's web page and has a local cache, and the OOD dec is updated or uninstalled, the runtime may still open the old page for a short period (because the old page is cached locally). This may cause temporary inconsistency, and cache-control headers can be considered to control the local caching strategy later.

- For internal elements of the same URL, a series of "a" link requests are generated, which should all correspond to the same dir-id. If opening a complete web page is considered a session, then it should also correspond to the same dir-id for the same session. 
However, this presents a challenge: different elements within a session are loaded in order, and there may be some delayed dynamic loading. If a timeout refresh is triggered during this period, and the dir-id on the OOD changes due to dec updates, different versions of content may appear on the same page. This issue also exists in the Web 2.0 world. Do we need to address this situation? In theory, refreshing the page can solve the problem.

**Comment by lurenpluto** [comment]
In the cyfs-stack's internal app service manager, a cache based on (dec_id, version) to the corresponding web-dir has been added, with the following mechanism:

- The (dec_id, version) -> Option<dir-id> queried from OOD will be cached, with the default cache timeout being 10 minutes.
- When the cyfs-stack front module processes incoming a-link requests, it decides whether to refresh based on the request's cache-control header. If the header specifies values such as no-cache, no-store, or must-revalidate, a forced refresh will be triggered. However, the refresh still has a minimum interval, which is currently set to 1 minute by default.

See at 1fb3857bee27e9ca58ff53710074804fc5a648e7

**Comment by lizhihongTest** [comment]
@lurenpluto It's a great improvement，A-link loading static web pages has significantly improved performance
## Control group data before modification
Test results before modification: https://github.com/buckyos/CYFS/issues/149#issuecomment-1498569436
## Modified test results
### Test Environment
+ OOD Servcie : Nightly 1.1.0.744
+ CYFS Browser : Nightly  build by CYFS main branche lastest code 1fb3857
+ cyfs://a link : 200 images web,dec_app cyfs://5r4MYfFJ7ktzBzSi1sWmU7BJLgpEEdp8ukbWemsFuQc1/9tGpLNnCgANJ6PfqfQSAvLu2tVv4qLG1cFoTgZBEkNcG 
+ web page :  cyfs://a.3afs9n7yaxaxbxzw5l7aum09336dambv92ga2q935uairdhkc9/9tGpLNnCgANJ6PfqfQSAvLu2tVv4qLG1cFoTgZBEkNcG/index.html

### Test Result
+ First load time
```
200 requests
7.8 MB transferred
7.7 MB resources
Finish: 18.31 s
DOMContentLoaded: 1.52 s
Load: 18.31 s
```
+ Clear browser cache, second load time
```
200 requests
7.8 MB transferred
7.7 MB resources
Finish: 3.82 s
DOMContentLoaded: 125 ms
Load: 3.81 s
```

### Test Log
[cyfs_a_link_179_log.zip](https://github.com/buckyos/CYFS/files/11176857/cyfs_a_link_179_log.zip)

**Comment by lurenpluto** [comment]
Thanks for the test help provided! 

The first stage of the optimization of a protocol can be like this first, and further optimization will be carried out according to the needs in the future

Complete at 1fb3857bee27e9ca58ff53710074804fc5a648e7

**Comment by lurenpluto** [comment]
Regarding the optimization of Step 1 in the A link, issue #189 will have an impact. Once the optimization of op-env usage is completed, the first time opening of the A link will have further improvements.
