### ISSUE TITLE
NDN not recycle incomplete download tasks

### ISSUE THREAD

**Issue by lizhihongTest** [buckyos/CYFS#180]
**Describe the bug**

I found a large number of incomplete download tasks in my OOD when reviewing the gateway logs, NDN maybe not recycle incomplete download tasks

CYFS Stack seems to load unfinished tasks from download_task_tracker every time I reboot

**System information**
+ OOD Service : Nightly 1.1.0.744

**CYFS Stack log**
[gateway_88590_rCURRENT.log](https://github.com/buckyos/CYFS/files/11169525/gateway_88590_rCURRENT.log)
[gateway_bdt_88590_rCURRENT.log](https://github.com/buckyos/CYFS/files/11169527/gateway_bdt_88590_rCURRENT.log)
<details>
<summary>gateway log</summary>
Line 44: [2023-04-06 16:57:45.418008 +08:00] INFO [ThreadId(6)] [component/cyfs-bdt/src/ndn/chunk/manager.rs:146] ChunkManager:{local:5aSixgLox5CRLLaMcnsRz75A4khSXay5WRjfN5VjNNVx} create new cache ChunkCache{chunk:7C8WXUGwAUt74UZqVuNEYbh54DxhGd4XfUGpQsrzoBhk}
	Line 45: [2023-04-06 16:57:45.418085 +08:00] INFO [ThreadId(6)] [component/cyfs-bdt/src/ndn/chunk/manager.rs:155] ChunkManager:{local:5aSixgLox5CRLLaMcnsRz75A4khSXay5WRjfN5VjNNVx} create new downloader ChunkDownloader{chunk:7C8WXUGwAUt74UZqVuNEYbh54DxhGd4XfUGpQsrzoBhk}
	Line 47: [2023-04-06 16:57:45.418229 +08:00] INFO [ThreadId(4)] [component/cyfs-bdt/src/ndn/chunk/download.rs:312] ChunkDownloader{chunk:7C8WXUGwAUt74UZqVuNEYbh54DxhGd4XfUGpQsrzoBhk} begin load cache
	Line 48: [2023-04-06 16:57:45.419369 +08:00] INFO [ThreadId(6)] [component/cyfs-bdt/src/ndn/chunk/cache/stream.rs:88] ChunkStreamCache{chunk:7C8WXUGwAUt74UZqVuNEYbh54DxhGd4XfUGpQsrzoBhk} load finished:false
	Line 49: [2023-04-06 16:57:45.419496 +08:00] INFO [ThreadId(6)] [component/cyfs-bdt/src/ndn/chunk/download.rs:323] ChunkDownloader{chunk:7C8WXUGwAUt74UZqVuNEYbh54DxhGd4XfUGpQsrzoBhk} enter downloading
	Line 50: [2023-04-06 16:57:45.419563 +08:00] INFO [ThreadId(6)] [component/cyfs-bdt/src/ndn/chunk/download.rs:365] ChunkDownloader{chunk:7C8WXUGwAUt74UZqVuNEYbh54DxhGd4XfUGpQsrzoBhk} return sources from context, op_id=1969141036, sources=[DownloadSource { target: NamedObjectDesc { obj_type: 1, dec_id: None, ref_objects: None, prev: None, create_timestamp: None, create_time: None, expired_time: None, owner: Some(5r4MYfFQ1BcMPzkS4qPtUX69kYDXUU5iPbQpd62tEZ9N), area: Some(Area { country: 0, carrier: 0, city: 0, inner: 2 }), author: SubDescNone, public_key: Rsa(RSAPublicKey { n: BigUint { data: [3697358334900226327, 10643528594101915244, 7910719018645537593, 5261358610864114411, 14178965996295300794, 13512126982180310736, 5137736509902903664, 14612759755873038354, 5154429996688472820, 5494654742601378170, 12874883492128378353, 15390373710377554424, 6250884277597739634, 17269370410316641552, 5808475063396240677, 16858314078186702269] }, e: BigUint { data: [65537] } }), desc_content: DeviceDescContent { uniqu...
	Line 51: [2023-04-06 16:57:45.419660 +08:00] INFO [ThreadId(6)] [component/cyfs-bdt/src/ndn/chunk/download.rs:373] ChunkDownloader{chunk:7C8WXUGwAUt74UZqVuNEYbh54DxhGd4XfUGpQsrzoBhk} will exec op after queried source, query_id=1969141036, next_op=StartSession(StartSessionOp { op_id: IncreaseId(1969141037), update_at: 13320398943779000, source: DownloadSource { target: NamedObjectDesc { obj_type: 1, dec_id: None, ref_objects: None, prev: None, create_timestamp: None, create_time: None, expired_time: None, owner: Some(5r4MYfFQ1BcMPzkS4qPtUX69kYDXUU5iPbQpd62tEZ9N), area: Some(Area { country: 0, carrier: 0, city: 0, inner: 2 }), author: SubDescNone, public_key: Rsa(RSAPublicKey { n: BigUint { data: [3697358334900226327, 10643528594101915244, 7910719018645537593, 5261358610864114411, 14178965996295300794, 13512126982180310736, 5137736509902903664, 14612759755873038354, 5154429996688472820, 5494654742601378170, 12874883492128378353, 15390373710377554424, 6250884277597739634, 17269370410316641552, 58084750633...
	Line 52: [2023-04-06 16:57:45.419763 +08:00] INFO [ThreadId(6)] [component/cyfs-bdt/src/ndn/chunk/download.rs:378] ChunkDownloader{chunk:7C8WXUGwAUt74UZqVuNEYbh54DxhGd4XfUGpQsrzoBhk} will start session, op_id=1969141037
	Line 54: [2023-04-06 16:57:45.420002 +08:00] INFO [ThreadId(6)] [component/cyfs-bdt/src/ndn/chunk/download.rs:408] ChunkDownloader{chunk:7C8WXUGwAUt74UZqVuNEYbh54DxhGd4XfUGpQsrzoBhk} will start session, op_id=1969141037, session=DownloadSession{session_id:TempSeq(4185538650), chunk:7C8WXUGwAUt74UZqVuNEYbh54DxhGd4XfUGpQsrzoBhk, source:5aSixgNJ3dYDnadjdAGuGbLkRdFwT6EJbdpm4mnVE2H7}
	Line 54: [2023-04-06 16:57:45.420002 +08:00] INFO [ThreadId(6)] [component/cyfs-bdt/src/ndn/chunk/download.rs:408] ChunkDownloader{chunk:7C8WXUGwAUt74UZqVuNEYbh54DxhGd4XfUGpQsrzoBhk} will start session, op_id=1969141037, session=DownloadSession{session_id:TempSeq(4185538650), chunk:7C8WXUGwAUt74UZqVuNEYbh54DxhGd4XfUGpQsrzoBhk, source:5aSixgNJ3dYDnadjdAGuGbLkRdFwT6EJbdpm4mnVE2H7}
	Line 55: [2023-04-06 16:57:45.420079 +08:00] INFO [ThreadId(6)] [component/cyfs-bdt/src/ndn/channel/download.rs:188] DownloadSession{session_id:TempSeq(4185538650), chunk:7C8WXUGwAUt74UZqVuNEYbh54DxhGd4XfUGpQsrzoBhk, source:5aSixgNJ3dYDnadjdAGuGbLkRdFwT6EJbdpm4mnVE2H7} sent Interest { session_id: TempSeq(4185538650), chunk: ChunkId: "7C8WXUGwAUt74UZqVuNEYbh54DxhGd4XfUGpQsrzoBhk", prefer_type: Stream(Some(0), Some(2963), Some(1416)), referer: Some("{\"dec_id\":\"9tGpLNneAgioE6jbFGP1BdibbNosyjFmk8JNLMcNsAj1\",\"flags\":1,\"object_id\":\"7Tk94YfJTeW5hRgDqJCwdFAWDeB6PZUHWnLheqM8RCyq\",\"req_path\":\"/req_path/4N7HZAJ5WXxfyTR2QBKz/groupA/task0\"}"), from: None, group_path: Some("9tGpLNneAgioE6jbFGP1BdibbNosyjFmk8JNLMcNsAj1/group_path/4N7HZAJ5WXxfyTR2QBKz/groupA/2052402017") }
	Line 55: [2023-04-06 16:57:45.420079 +08:00] INFO [ThreadId(6)] [component/cyfs-bdt/src/ndn/channel/download.rs:188] DownloadSession{session_id:TempSeq(4185538650), chunk:7C8WXUGwAUt74UZqVuNEYbh54DxhGd4XfUGpQsrzoBhk, source:
[gateway_88590_rCURRENT.log](https://github.com/buckyos/CYFS/files/11169515/gateway_88590_rCURRENT.log)
[gateway_bdt_88590_rCURRENT.log](https://github.com/buckyos/CYFS/files/11169518/gateway_bdt_88590_rCURRENT.log)
5aSixgNJ3dYDnadjdAGuGbLkRdFwT6EJbdpm4mnVE2H7} sent Interest { session_id: TempSeq(4185538650), chunk: ChunkId: "7C8WXUGwAUt74UZqVuNEYbh54DxhGd4XfUGpQsrzoBhk", prefer_type: Stream(Some(0), Some(2963), Some(1416)), referer: Some("{\"dec_id\":\"9tGpLNneAgioE6jbFGP1BdibbNosyjFmk8JNLMcNsAj1\",\"flags\":1,\"object_id\":\"7Tk94YfJTeW5hRgDqJCwdFAWDeB6PZUHWnLheqM8RCyq\",\"req_path\":\"/req_path/4N7HZAJ5WXxfyTR2QBKz/groupA/task0\"}"), from: None, group_path: Some("9tGpLNneAgioE6jbFGP1BdibbNosyjFmk8JNLMcNsAj1/group_path/4N7HZAJ5WXxfyTR2QBKz/groupA/2052402017") }
	Line 229: [2023-04-06 16:57:45.925405 +08:00] INFO [ThreadId(6)] [component/cyfs-bdt/src/ndn/channel/download.rs:410] DownloadSession{session_id:TempSeq(4185538650), chunk:7C8WXUGwAUt74UZqVuNEYbh54DxhGd4XfUGpQsrzoBhk, source:5aSixgNJ3dYDnadjdAGuGbLkRdFwT6EJbdpm4mnVE2H7} sent Interest { session_id: TempSeq(4185538650), chunk: ChunkId: "7C8WXUGwAUt74UZqVuNEYbh54DxhGd4XfUGpQsrzoBhk", prefer_type: Stream(Some(0), Some(2963), Some(1416)), referer: Some("{\"dec_id\":\"9tGpLNneAgioE6jbFGP1BdibbNosyjFmk8JNLMcNsAj1\",\"flags\":1,\"object_id\":\"7Tk94YfJTeW5hRgDqJCwdFAWDeB6PZUHWnLheqM8RCyq\",\"req_path\":\"/req_path/4N7HZAJ5WXxfyTR2QBKz/groupA/task0\"}"), from: None, group_path: None }
	Line 229: [2023-04-06 16:57:45.925405 +08:00] INFO [ThreadId(6)] [component/cyfs-bdt/src/ndn/channel/download.rs:410] DownloadSession{session_id:TempSeq(4185538650), chunk:7C8WXUGwAUt74UZqVuNEYbh54DxhGd4XfUGpQsrzoBhk, source:5aSixgNJ3dYDnadjdAGuGbLkRdFwT6EJbdpm4mnVE2H7} sent Interest { session_id: TempSeq(4185538650), chunk: ChunkId: "7C8WXUGwAUt74UZqVuNEYbh54DxhGd4XfUGpQsrzoBhk", prefer_type: Stream(Some(0), Some(2963), Some(1416)), referer: Some("{\"dec_id\":\"9tGpLNneAgioE6jbFGP1BdibbNosyjFmk8JNLMcNsAj1\",\"flags\":1,\"object_id\":\"7Tk94YfJTeW5hRgDqJCwdFAWDeB6PZUHWnLheqM8RCyq\",\"req_path\":\"/req_path/4N7HZAJ5WXxfyTR2QBKz/groupA/task0\"}"), from: None, group_path: None }
	Line 508: [2023-04-06 16:57:46.931230 +08:00] INFO [ThreadId(3)] [component/cyfs-bdt/src/ndn/channel/download.rs:410] DownloadSession{session_id:TempSeq(4185538650), chunk:7C8WXUGwAUt74UZqVuNEYbh54DxhGd4XfUGpQsrzoBhk, source:5aSixgNJ3dYDnadjdAGuGbLkRdFwT6EJbdpm4mnVE2H7} sent Interest { session_id: TempSeq(4185538650), chunk: ChunkId: "7C8WXUGwAUt74UZqVuNEYbh54DxhGd4XfUGpQsrzoBhk", prefer_type: Stream(Some(0), Some(2963), Some(1416)), referer: Some("{\"dec_id\":\"9tGpLNneAgioE6jbFGP1BdibbNosyjFmk8JNLMcNsAj1\",\"flags\":1,\"object_id\":\"7Tk94YfJTeW5hRgDqJCwdFAWDeB6PZUHWnLheqM8RCyq\",\"req_path\":\"/req_path/4N7HZAJ5WXxfyTR2QBKz/groupA/task0\"}"), from: None, group_path: None }
	Line 508: [2023-04-06 16:57:46.931230 +08:00] INFO [ThreadId(3)] [component/cyfs-bdt/src/ndn/channel/download.rs:410] DownloadSession{session_id:TempSeq(4185538650), chunk:7C8WXUGwAUt74UZqVuNEYbh54DxhGd4XfUGpQsrzoBhk, source:5aSixgNJ3dYDnadjdAGuGbLkRdFwT6EJbdpm4mnVE2H7} sent Interest { session_id: TempSeq(4185538650), chunk: ChunkId: "7C8WXUGwAUt74UZqVuNEYbh54DxhGd4XfUGpQsrzoBhk", prefer_type: Stream(Some(0), Some(2963), Some(1416)), referer: Some("{\"dec_id\":\"9tGpLNneAgioE6jbFGP1BdibbNosyjFmk8JNLMcNsAj1\",\"flags\":1,\"object_id\":\"7Tk94YfJTeW5hRgDqJCwdFAWDeB6PZUHWnLheqM8RCyq\",\"req_path\":\"/req_path/4N7HZAJ5WXxfyTR2QBKz/groupA/task0\"}"), from: None, group_path: None }
	Line 763: [2023-04-06 16:57:48.938759 +08:00] INFO [ThreadId(6)] [component/cyfs-bdt/src/ndn/channel/download.rs:410] DownloadSession{session_id:TempSeq(4185538650), chunk:7C8WXUGwAUt74UZqVuNEYbh54DxhGd4XfUGpQsrzoBhk, source:5aSixgNJ3dYDnadjdAGuGbLkRdFwT6EJbdpm4mnVE2H7} sent Interest { session_id: TempSeq(4185538650), chunk: ChunkId: "7C8WXUGwAUt74UZqVuNEYbh54DxhGd4XfUGpQsrzoBhk", prefer_type: Stream(Some(0), Some(2963), Some(1416)), referer: Some("{\"dec_id\":\"9tGpLNneAgioE6jbFGP1BdibbNosyjFmk8JNLMcNsAj1\",\"flags\":1,\"object_id\":\"7Tk94YfJTeW5hRgDqJCwdFAWDeB6PZUHWnLheqM8RCyq\",\"req_path\":\"/req_path/4N7HZAJ5WXxfyTR2QBKz/groupA/task0\"}"), from: None, group_path: None }
	Line 763: [2023-04-06 16:57:48.938759 +08:00] INFO [ThreadId(6)] [component/cyfs-bdt/src/ndn/channel/download.rs:410] DownloadSession{session_id:TempSeq(4185538650), chunk:7C8WXUGwAUt74UZqVuNEYbh54DxhGd4XfUGpQsrzoBhk, source:5aSixgNJ3dYDnadjdAGuGbLkRdFwT6EJbdpm4mnVE2H7} sent Interest { session_id: TempSeq(4185538650), chunk: ChunkId: "7C8WXUGwAUt74UZqVuNEYbh54DxhGd4XfUGpQsrzoBhk", prefer_type: Stream(Some(0), Some(2963), Some(1416)), referer: Some("{\"dec_id\":\"9tGpLNneAgioE6jbFGP1BdibbNosyjFmk8JNLMcNsAj1\",\"flags\":1,\"object_id\":\"7Tk94YfJTeW5hRgDqJCwdFAWDeB6PZUHWnLheqM8RCyq\",\"req_path\":\"/req_path/4N7HZAJ5WXxfyTR2QBKz/groupA/task0\"}"), from: None, group_path: None }
	Line 894: [2023-04-06 16:57:52.939006 +08:00] INFO [ThreadId(4)] [component/cyfs-bdt/src/ndn/channel/download.rs:410] DownloadSession{session_id:TempSeq(4185538650), chunk:7C8WXUGwAUt74UZqVuNEYbh54DxhGd4XfUGpQsrzoBhk, source:5aSixgNJ3dYDnadjdAGuGbLkRdFwT6EJbdpm4mnVE2H7} sent Interest { session_id: TempSeq(4185538650), chunk: ChunkId: "7C8WXUGwAUt74UZqVuNEYbh54DxhGd4XfUGpQsrzoBhk", prefer_type: Stream(Some(0), Some(2963), Some(1416)), referer: Some("{\"dec_id\":\"9tGpLNneAgioE6jbFGP1BdibbNosyjFmk8JNLMcNsAj1\",\"flags\":1,\"object_id\":\"7Tk94YfJTeW5hRgDqJCwdFAWDeB6PZUHWnLheqM8RCyq\",\"req_path\":\"/req_path/4N7HZAJ5WXxfyTR2QBKz/groupA/task0\"}"), from: None, group_path: None }
	Line 894: [2023-04-06 16:57:52.939006 +08:00] INFO [ThreadId(4)] [component/cyfs-bdt/src/ndn/channel/download.rs:410] DownloadSession{session_id:TempSeq(4185538650), chunk:7C8WXUGwAUt74UZqVuNEYbh54DxhGd4XfUGpQsrzoBhk, source:5aSixgNJ3dYDnadjdAGuGbLkRdFwT6EJbdpm4mnVE2H7} sent Interest { session_id: TempSeq(4185538650), chunk: ChunkId: "7C8WXUGwAUt74UZqVuNEYbh54DxhGd4XfUGpQsrzoBhk", prefer_type: Stream(Some(0), Some(2963), Some(1416)), referer: Some("{\"dec_id\":\"9tGpLNneAgioE6jbFGP1BdibbNosyjFmk8JNLMcNsAj1\",\"flags\":1,\"object_id\":\"7Tk94YfJTeW5hRgDqJCwdFAWDeB6PZUHWnLheqM8RCyq\",\"req_path\":\"/req_path/4N7HZAJ5WXxfyTR2QBKz/groupA/task0\"}"), from: None, group_path: None }
	Line 1070: [2023-04-06 16:58:00.946034 +08:00] INFO [ThreadId(3)] [component/cyfs-bdt/src/ndn/channel/download.rs:410] DownloadSession{session_id:TempSeq(4185538650), chunk:7C8WXUGwAUt74UZqVuNEYbh54DxhGd4XfUGpQsrzoBhk, source:5aSixgNJ3dYDnadjdAGuGbLkRdFwT6EJbdpm4mnVE2H7} sent Interest { session_id: TempSeq(4185538650), chunk: ChunkId: "7C8WXUGwAUt74UZqVuNEYbh54DxhGd4XfUGpQsrzoBhk", prefer_type: Stream(Some(0), Some(2963), Some(1416)), referer: Some("{\"dec_id\":\"9tGpLNneAgioE6jbFGP1BdibbNosyjFmk8JNLMcNsAj1\",\"flags\":1,\"object_id\":\"7Tk94YfJTeW5hRgDqJCwdFAWDeB6PZUHWnLheqM8RCyq\",\"req_path\":\"/req_path/4N7HZAJ5WXxfyTR2QBKz/groupA/task0\"}"), from: None, group_path: None }
	Line 1070: [2023-04-06 16:58:00.946034 +08:00] INFO [ThreadId(3)] [component/cyfs-bdt/src/ndn/channel/download.rs:410] DownloadSession{session_id:TempSeq(4185538650), chunk:7C8WXUGwAUt74UZqVuNEYbh54DxhGd4XfUGpQsrzoBhk, source:5aSixgNJ3dYDnadjdAGuGbLkRdFwT6EJbdpm4mnVE2H7} sent Interest { session_id: TempSeq(4185538650), chunk: ChunkId: "7C8WXUGwAUt74UZqVuNEYbh54DxhGd4XfUGpQsrzoBhk", prefer_type: Stream(Some(0), Some(2963), Some(1416)), referer: Some("{\"dec_id\":\"9tGpLNneAgioE6jbFGP1BdibbNosyjFmk8JNLMcNsAj1\",\"flags\":1,\"object_id\":\"7Tk94YfJTeW5hRgDqJCwdFAWDeB6PZUHWnLheqM8RCyq\",\"req_path\":\"/req_path/4N7HZAJ5WXxfyTR2QBKz/groupA/task0\"}"), from: None, group_path: None }
	Line 1202: [2023-04-06 16:58:16.956166 +08:00] INFO [ThreadId(2)] [component/cyfs-bdt/src/ndn/channel/download.rs:410] DownloadSession{session_id:TempSeq(4185538650), chunk:7C8WXUGwAUt74UZqVuNEYbh54DxhGd4XfUGpQsrzoBhk, source:5aSixgNJ3dYDnadjdAGuGbLkRdFwT6EJbdpm4mnVE2H7} sent Interest { session_id: TempSeq(4185538650), chunk: ChunkId: "7C8WXUGwAUt74UZqVuNEYbh54DxhGd4XfUGpQsrzoBhk", prefer_type: Stream(Some(0), Some(2963), Some(1416)), referer: Some("{\"dec_id\":\"9tGpLNneAgioE6jbFGP1BdibbNosyjFmk8JNLMcNsAj1\",\"flags\":1,\"object_id\":\"7Tk94YfJTeW5hRgDqJCwdFAWDeB6PZUHWnLheqM8RCyq\",\"req_path\":\"/req_path/4N7HZAJ5WXxfyTR2QBKz/groupA/task0\"}"), from: None, group_path: None }
	Line 1202: [2023-04-06 16:58:16.956166 +08:00] INFO [ThreadId(2)] [component/cyfs-bdt/src/ndn/channel/download.rs:410] DownloadSession{session_id:TempSeq(4185538650), chunk:7C8WXUGwAUt74UZqVuNEYbh54DxhGd4XfUGpQsrzoBhk, source:5aSixgNJ3dYDnadjdAGuGbLkRdFwT6EJbdpm4mnVE2H7} sent Interest { session_id: TempSeq(4185538650), chunk: ChunkId: "7C8WXUGwAUt74UZqVuNEYbh54DxhGd4XfUGpQsrzoBhk", prefer_type: Stream(Some(0), Some(2963), Some(1416)), referer: Some("{\"dec_id\":\"9tGpLNneAgioE6jbFGP1BdibbNosyjFmk8JNLMcNsAj1\",\"flags\":1,\"object_id\":\"7Tk94YfJTeW5hRgDqJCwdFAWDeB6PZUHWnLheqM8RCyq\",\"req_path\":\"/req_path/4N7HZAJ5WXxfyTR2QBKz/groupA/task0\"}"), from: None, group_path: None }
	Line 1341: [2023-04-06 16:58:48.959719 +08:00] INFO [ThreadId(3)] [component/cyfs-bdt/src/ndn/channel/download.rs:410] DownloadSession{session_id:TempSeq(4185538650), chunk:7C8WXUGwAUt74UZqVuNEYbh54DxhGd4XfUGpQsrzoBhk, source:5aSixgNJ3dYDnadjdAGuGbLkRdFwT6EJbdpm4mnVE2H7} sent Interest { session_id: TempSeq(4185538650), chunk: ChunkId: "7C8WXUGwAUt74UZqVuNEYbh54DxhGd4XfUGpQsrzoBhk", prefer_type: Stream(Some(0), Some(2963), Some(1416)), referer: Some("{\"dec_id\":\"9tGpLNneAgioE6jbFGP1BdibbNosyjFmk8JNLMcNsAj1\",\"flags\":1,\"object_id\":\"7Tk94YfJTeW5hRgDqJCwdFAWDeB6PZUHWnLheqM8RCyq\",\"req_path\":\"/req_path/4N7HZAJ5WXxfyTR2QBKz/groupA/task0\"}"), from: None, group_path: None }
	Line 1341: [2023-04-06 16:58:48.959719 +08:00] INFO [ThreadId(3)] [component/cyfs-bdt/src/ndn/channel/download.rs:410] DownloadSession{session_id:TempSeq(4185538650), chunk:7C8WXUGwAUt74UZqVuNEYbh54DxhGd4XfUGpQsrzoBhk, source:5aSixgNJ3dYDnadjdAGuGbLkRdFwT6EJbdpm4mnVE2H7} sent Interest { session_id: TempSeq(4185538650), chunk: ChunkId: "7C8WXUGwAUt74UZqVuNEYbh54DxhGd4XfUGpQsrzoBhk", prefer_type: Stream(Some(0), Some(2963), Some(1416)), referer: Some("{\"dec_id\":\"9tGpLNneAgioE6jbFGP1BdibbNosyjFmk8JNLMcNsAj1\",\"flags\":1,\"object_id\":\"7Tk94YfJTeW5hRgDqJCwdFAWDeB6PZUHWnLheqM8RCyq\",\"req_path\":\"/req_path/4N7HZAJ5WXxfyTR2QBKz/groupA/task0\"}"), from: None, group_path: None }
	Line 1526: [2023-04-06 16:59:52.962850 +08:00] INFO [ThreadId(6)] [component/cyfs-bdt/src/ndn/channel/download.rs:410] DownloadSession{session_id:TempSeq(4185538650), chunk:7C8WXUGwAUt74UZqVuNEYbh54DxhGd4XfUGpQsrzoBhk, source:5aSixgNJ3dYDnadjdAGuGbLkRdFwT6EJbdpm4mnVE2H7} sent Interest { session_id: TempSeq(4185538650), chunk: ChunkId: "7C8WXUGwAUt74UZqVuNEYbh54DxhGd4XfUGpQsrzoBhk", prefer_type: Stream(Some(0), Some(2963), Some(1416)), referer: Some("{\"dec_id\":\"9tGpLNneAgioE6jbFGP1BdibbNosyjFmk8JNLMcNsAj1\",\"flags\":1,\"object_id\":\"7Tk94YfJTeW5hRgDqJCwdFAWDeB6PZUHWnLheqM8RCyq\",\"req_path\":\"/req_path/4N7HZAJ5WXxfyTR2QBKz/groupA/task0\"}"), from: None, group_path: None }
	Line 1526: [2023-04-06 16:59:52.962850 +08:00] INFO [ThreadId(6)] [component/cyfs-bdt/src/ndn/channel/download.rs:410] DownloadSession{session_id:TempSeq(4185538650), chunk:7C8WXUGwAUt74UZqVuNEYbh54DxhGd4XfUGpQsrzoBhk, source:5aSixgNJ3dYDnadjdAGuGbLkRdFwT6EJbdpm4mnVE2H7} sent Interest { session_id: TempSeq(4185538650), chunk: ChunkId: "7C8WXUGwAUt74UZqVuNEYbh54DxhGd4XfUGpQsrzoBhk", prefer_type: Stream(Some(0), Some(2963), Some(1416)), referer: Some("{\"dec_id\":\"9tGpLNneAgioE6jbFGP1BdibbNosyjFmk8JNLMcNsAj1\",\"flags\":1,\"object_id\":\"7Tk94YfJTeW5hRgDqJCwdFAWDeB6PZUHWnLheqM8RCyq\",\"req_path\":\"/req_path/4N7HZAJ5WXxfyTR2QBKz/groupA/task0\"}"), from: None, group_path: None }
	Line 1784: [2023-04-06 17:02:00.967590 +08:00] INFO [ThreadId(3)] [component/cyfs-bdt/src/ndn/channel/download.rs:410] DownloadSession{session_id:TempSeq(4185538650), chunk:7C8WXUGwAUt74UZqVuNEYbh54DxhGd4XfUGpQsrzoBhk, source:5aSixgNJ3dYDnadjdAGuGbLkRdFwT6EJbdpm4mnVE2H7} sent Interest { session_id: TempSeq(4185538650), chunk: ChunkId: "7C8WXUGwAUt74UZqVuNEYbh54DxhGd4XfUGpQsrzoBhk", prefer_type: Stream(Some(0), Some(2963), Some(1416)), referer: Some("{\"dec_id\":\"9tGpLNneAgioE6jbFGP1BdibbNosyjFmk8JNLMcNsAj1\",\"flags\":1,\"object_id\":\"7Tk94YfJTeW5hRgDqJCwdFAWDeB6PZUHWnLheqM8RCyq\",\"req_path\":\"/req_path/4N7HZAJ5WXxfyTR2QBKz/groupA/task0\"}"), from: None, group_path: None }
	Line 1784: [2023-04-06 17:02:00.967590 +08:00] INFO [ThreadId(3)] [component/cyfs-bdt/src/ndn/channel/download.rs:410] DownloadSession{session_id:TempSeq(4185538650), chunk:7C8WXUGwAUt74UZqVuNEYbh54DxhGd4XfUGpQsrzoBhk, source:5aSixgNJ3dYDnadjdAGuGbLkRdFwT6EJbdpm4mnVE2H7} sent Interest { session_id: TempSeq(4185538650), chunk: ChunkId: "7C8WXUGwAUt74UZqVuNEYbh54DxhGd4XfUGpQsrzoBhk", prefer_type: Stream(Some(0), Some(2963), Some(1416)), referer: Some("{\"dec_id\":\"9tGpLNneAgioE6jbFGP1BdibbNosyjFmk8JNLMcNsAj1\",\"flags\":1,\"object_id\":\"7Tk94YfJTeW5hRgDqJCwdFAWDeB6PZUHWnLheqM8RCyq\",\"req_path\":\"/req_path/4N7HZAJ5WXxfyTR2QBKz/groupA/task0\"}"), from: None, group_path: None }
	Line 2225: [2023-04-06 17:06:16.968368 +08:00] INFO [ThreadId(2)] [component/cyfs-bdt/src/ndn/channel/download.rs:410] DownloadSession{session_id:TempSeq(4185538650), chunk:7C8WXUGwAUt74UZqVuNEYbh54DxhGd4XfUGpQsrzoBhk, source:5aSixgNJ3dYDnadjdAGuGbLkRdFwT6EJbdpm4mnVE2H7} sent Interest { session_id: TempSeq(4185538650), chunk: ChunkId: "7C8WXUGwAUt74UZqVuNEYbh54DxhGd4XfUGpQsrzoBhk", prefer_type: Stream(Some(0), Some(2963), Some(1416)), referer: Some("{\"dec_id\":\"9tGpLNneAgioE6jbFGP1BdibbNosyjFmk8JNLMcNsAj1\",\"flags\":1,\"object_id\":\"7Tk94YfJTeW5hRgDqJCwdFAWDeB6PZUHWnLheqM8RCyq\",\"req_path\":\"/req_path/4N7HZAJ5WXxfyTR2QBKz/groupA/task0\"}"), from: None, group_path: None }
	Line 2225: [2023-04-06 17:06:16.968368 +08:00] INFO [ThreadId(2)] [component/cyfs-bdt/src/ndn/channel/download.rs:410] DownloadSession{session_id:TempSeq(4185538650), chunk:7C8WXUGwAUt74UZqVuNEYbh54DxhGd4XfUGpQsrzoBhk, source:5aSixgNJ3dYDnadjdAGuGbLkRdFwT6EJbdpm4mnVE2H7} sent Interest { session_id: TempSeq(4185538650), chunk: ChunkId: "7C8WXUGwAUt74UZqVuNEYbh54DxhGd4XfUGpQsrzoBhk", prefer_type: Stream(Some(0), Some(2963), Some(1416)), referer: Some("{\"dec_id\":\"9tGpLNneAgioE6jbFGP1BdibbNosyjFmk8JNLMcNsAj1\",\"flags\":1,\"object_id\":\"7Tk94YfJTeW5hRgDqJCwdFAWDeB6PZUHWnLheqM8RCyq\",\"req_path\":\"/req_path/4N7HZAJ5WXxfyTR2QBKz/groupA/task0\"}"), from: None, group_path: None }
</details>

**Comment by lurenpluto** [comment]
Currently, there are two types of download tasks in the cyfs-stack:

# 1. Tasks initiated based on NDN
including the following two interfaces:
## a. stack.ndn.get_data 
the most basic interface that allows downloading data based on file/chunk granularity and simultaneously creates a download task.
## b. a/r/o protocol in the front module 
if the target request is a Chunk/File and the mode is set to default or data, it will ultimately be redirected to ndn.get_data, creating a corresponding download task.

The download tasks created by this category of interfaces are considered "lightweight" tasks. They usually return a stream directly, and control over these tasks is limited or not available. If the task fails, is canceled, or the protocol stack is restarted, the task will not retain its state and will not continue to execute.

# 2. Tasks initiated based on the trans interface
These tasks are considered "heavyweight" download tasks. They can be created through the trans.create_task interface, and the cyfs-stack internally manages them using the TaskManager. These tasks are persistent and provide more complex control mechanisms, such as start/pause/query status, etc. By default, uncompleted tasks will automatically start and continue transferring after the protocol stack starts.


From your logs, it appears that the download tasks initiated after the cyfs-stack restart are managed by the TaskManager, so they should be the second type of "heavyweight" tasks. These tasks have an unfinished status, which is why they continue. If you need to cancel them, you need to explicitly call the trans interface to control them from outside.
