### ISSUE TITLE
Errors and Panic occurs in bdt during a stress test case

### ISSUE THREAD

**Issue by lurenpluto** [buckyos/CYFS#188]
I wrote a stress test case called isolate-path-env and ran it in the zone-simulator. During the test, there is a period of extremely high memory and CPU usage, which then goes down. However, some issues were found with the bdt module during this process:

1. There are always various connection timeout issues, and they persist even after the CPU usage goes down in the later stage of the stress test.
2. A panic occurred in the end.

During the test, due to performance reasons, the log level was adjusted to the warn level, so some logs might be missing. The corresponding logs can be found in the attachment.

The panic backtrace as follows:

<details><summary>Details</summary>
<p>

[2023-04-08 18:11:17.143806] WARN [ThreadId(3)] [cyfs_debug::panic::panic] thread 'async-std/runtime' panicked at 'called `Option::unwrap()` on a `None` value': component\cyfs-bdt\src\stream\manager.rs:351
   0: backtrace::backtrace::dbghelp::trace
             at C:\Users\LUREN\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.67\src\backtrace\dbghelp.rs:98
   1: backtrace::backtrace::trace_unsynchronized
             at C:\Users\LUREN\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.67\src\backtrace\mod.rs:66
   2: backtrace::backtrace::trace<backtrace::capture::impl$1::create::closure_env$0>
             at C:\Users\LUREN\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.67\src\backtrace\mod.rs:53
   3: backtrace::capture::Backtrace::create
             at C:\Users\LUREN\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.67\src\capture.rs:176
   4: backtrace::capture::Backtrace::new
             at C:\Users\LUREN\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.67\src\capture.rs:140
   5: cyfs_debug::panic::manager::impl$1::start::closure$0
             at H:\work\CYFS_PUBLIC\src\component\cyfs-debug\src\panic\manager.rs:78
   6: alloc::boxed::impl$47::call
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\alloc\src\boxed.rs:2001
   7: std::panicking::rust_panic_with_hook
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\std\src\panicking.rs:692
   8: std::panicking::begin_panic_handler::closure$0
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\std\src\panicking.rs:577
   9: std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\std\src\sys_common\backtrace.rs:137
  10: std::panicking::begin_panic_handler
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\std\src\panicking.rs:575
  11: core::panicking::panic_fmt
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\core\src\panicking.rs:65
  12: core::panicking::panic
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\core\src\panicking.rs:115
  13: enum2$<core::option::Option<cyfs_bdt::tunnel::container::TunnelGuard> >::unwrap
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943\library\core\src\option.rs:778
  14: cyfs_bdt::stream::manager::impl$10::on_package
             at H:\work\CYFS_PUBLIC\src\component\cyfs-bdt\src\stream\manager.rs:351
  15: cyfs_bdt::tunnel::container::impl$15::on_package
             at H:\work\CYFS_PUBLIC\src\component\cyfs-bdt\src\tunnel\container.rs:1221
  16: core::future::from_generator::impl$1::poll<enum2$<cyfs_bdt::tunnel::tcp::impl$1::recv_inner::async_fn_env$0> >
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943\library\core\src\future\mod.rs:91
  17: futures_util::abortable::impl$6::poll::closure$0
             at C:\Users\LUREN\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.27\src\abortable.rs:170
  18: futures_util::abortable::Abortable<core::future::from_generator::GenFuture<enum2$<cyfs_bdt::tunnel::tcp::impl$1::recv_inner::async_fn_env$0> > >::try_poll
             at C:\Users\LUREN\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.27\src\abortable.rs:144
  19: futures_util::abortable::impl$6::poll
             at C:\Users\LUREN\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.27\src\abortable.rs:170
  20: async_std::task::builder::impl$1::poll::closure$0
             at C:\Users\LUREN\.cargo\registry\src\github.com-1ecc6299db9ec823\async-std-1.12.0\src\task\builder.rs:199
  21: async_std::task::task_locals_wrapper::impl$0::set_current::closure$0
             at C:\Users\LUREN\.cargo\registry\src\github.com-1ecc6299db9ec823\async-std-1.12.0\src\task\task_locals_wrapper.rs:60
  22: std::thread::local::LocalKey<core::cell::Cell<ptr_const$<async_std::task::task_locals_wrapper::TaskLocalsWrapper> > >::try_with
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943\library\std\src\thread\local.rs:446
  23: std::thread::local::LocalKey<core::cell::Cell<ptr_const$<async_std::task::task_locals_wrapper::TaskLocalsWrapper> > >::with<core::cell::Cell<ptr_const$<async_std::task::task_locals_wrapper::TaskLocalsWrapper> >,async_std::task::task_locals_wrapper::impl$0
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943\library\std\src\thread\local.rs:422
  24: async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current
             at C:\Users\LUREN\.cargo\registry\src\github.com-1ecc6299db9ec823\async-std-1.12.0\src\task\task_locals_wrapper.rs:55
  25: async_std::task::builder::impl$1::poll
             at C:\Users\LUREN\.cargo\registry\src\github.com-1ecc6299db9ec823\async-std-1.12.0\src\task\builder.rs:197
  26: async_executor::impl$4::spawn::async_block$0
             at C:\Users\LUREN\.cargo\registry\src\github.com-1ecc6299db9ec823\async-executor-1.5.0\src\lib.rs:139
  27: core::future::from_generator::impl$1::poll<enum2$<async_executor::impl$4::spawn::async_block_env$0<enum2$<core::result::Result<tuple$<>,futures_util::abortable::Aborted> >,async_std::task::builder::SupportTaskLocals<futures_util::abortable::Abortable<core
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943\library\core\src\future\mod.rs:91
  28: core::future::future::impl$1::poll
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943\library\core\src\future\future.rs:124
  29: async_task::raw::RawTask<core::pin::Pin<alloc::boxed::Box<core::future::from_generator::GenFuture<enum2$<async_executor::impl$4::spawn::async_block_env$0<enum2$<core::result::Result<tuple$<>,futures_util::abortable::Aborted> >,async_std::task::builder::Su
             at C:\Users\LUREN\.cargo\registry\src\github.com-1ecc6299db9ec823\async-task-4.3.0\src\raw.rs:511
  30: async_executor::impl$4::run::async_fn$0::async_block$0
             at C:\Users\LUREN\.cargo\registry\src\github.com-1ecc6299db9ec823\async-executor-1.5.0\src\lib.rs:230
  31: core::future::from_generator::impl$1::poll<enum2$<async_executor::impl$4::run::async_fn$0::async_block_env$0<tuple$<>,core::future::from_generator::GenFuture<enum2$<async_global_executor::threading::thread_main_loop::closure$1::closure$0::async_block_env$
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943\library\core\src\future\mod.rs:91
  32: futures_lite::future::impl$12::poll
             at C:\Users\LUREN\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-lite-1.12.0\src\future.rs:529
  33: async_executor::impl$4::run::async_fn$0
             at C:\Users\LUREN\.cargo\registry\src\github.com-1ecc6299db9ec823\async-executor-1.5.0\src\lib.rs:237
  34: core::future::from_generator::impl$1::poll<enum2$<async_executor::impl$4::run::async_fn_env$0<tuple$<>,futures_lite::future::Pending<tuple$<> > > > >             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943\library\core\src\future\mod.rs:91
  35: futures_lite::future::impl$12::poll
             at C:\Users\LUREN\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-lite-1.12.0\src\future.rs:529
  36: async_io::driver::block_on<tuple$<>,futures_lite::future::Or<core::future::from_generator::GenFuture<enum2$<async_executor::impl$9::run::async_fn_env$0<tuple$<>,core::future::from_generator::GenFuture<enum2$<async_global_executor::threading::thread_main_l
             at C:\Users\LUREN\.cargo\registry\src\github.com-1ecc6299db9ec823\async-io-1.12.0\src\driver.rs:146
  37: async_global_executor::reactor::block_on::closure$0
             at C:\Users\LUREN\.cargo\registry\src\github.com-1ecc6299db9ec823\async-global-executor-2.3.1\src\reactor.rs:3
  38: async_global_executor::reactor::block_on
             at C:\Users\LUREN\.cargo\registry\src\github.com-1ecc6299db9ec823\async-global-executor-2.3.1\src\reactor.rs:12
  39: async_global_executor::threading::thread_main_loop::closure$1::closure$0
             at C:\Users\LUREN\.cargo\registry\src\github.com-1ecc6299db9ec823\async-global-executor-2.3.1\src\threading.rs:95
  40: std::thread::local::LocalKey<async_executor::LocalExecutor>::try_with
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943\library\std\src\thread\local.rs:446
  41: std::thread::local::LocalKey<async_executor::LocalExecutor>::with
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943\library\std\src\thread\local.rs:422
  42: async_global_executor::threading::thread_main_loop::closure$1
             at C:\Users\LUREN\.cargo\registry\src\github.com-1ecc6299db9ec823\async-global-executor-2.3.1\src\threading.rs:89
  43: std::panicking::try::do_call
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943\library\std\src\panicking.rs:483
  44: std::panicking::try<tuple$<>,async_global_executor::threading::thread_main_loop::closure_env$1>
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943\library\std\src\panicking.rs:447
  45: std::panic::catch_unwind
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943\library\std\src\panic.rs:137
  46: async_global_executor::threading::thread_main_loop
             at C:\Users\LUREN\.cargo\registry\src\github.com-1ecc6299db9ec823\async-global-executor-2.3.1\src\threading.rs:88
  47: core::ops::function::FnOnce::call_once
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943\library\core\src\ops\function.rs:251
  48: std::sys_common::backtrace::__rust_begin_short_backtrace<void (*)(),tuple$<> >
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943\library\std\src\sys_common\backtrace.rs:121
  49: std::thread::impl$0::spawn_unchecked_::closure$1::closure$0
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943\library\std\src\thread\mod.rs:551
  50: core::panic::unwind_safe::impl$23::call_once
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943\library\core\src\panic\unwind_safe.rs:271
  51: std::panicking::try::do_call
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943\library\std\src\panicking.rs:483
  52: std::panicking::try
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943\library\std\src\panicking.rs:447
  53: std::panic::catch_unwind
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943\library\std\src\panic.rs:137
  54: std::thread::impl$0::spawn_unchecked_::closure$1
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943\library\std\src\thread\mod.rs:550
  55: core::ops::function::FnOnce::call_once<std::thread::impl$0::spawn_unchecked_::closure_env$1<void (*)(),tuple$<> >,tuple$<> >
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943\library\core\src\ops\function.rs:251
  56: alloc::boxed::impl$45::call_once
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\alloc\src\boxed.rs:1987
  57: alloc::boxed::impl$45::call_once
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\alloc\src\boxed.rs:1987
  58: std::sys::windows::thread::impl$0::new::thread_start
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\std\src\sys\windows\thread.rs:56
  59: BaseThreadInitThunk
  60: RtlUserThreadStart

</p>
</details> 

[cyfs-stack-test.zip](https://github.com/buckyos/CYFS/files/11183012/cyfs-stack-test.zip)

**Comment by lurenpluto** [comment]
The test case code has been submitted. To reproduce the issue, you can directly use this version of the code, compile the release version of the cyfs-stack-test project, and run it.

See at b89406bea53613192dd64faa31006c4c6c3951fc

To make it easier to locate the problem, I have adjusted the log level of the bdt module to info. Attached is a new set of logs.

[cyfs-stack-test.zip](https://github.com/buckyos/CYFS/files/11183081/cyfs-stack-test.zip)

**Comment by photosssa** [comment]
When start connection on low resource， tunnel guard may got released for no reference； Fix it on commit beed2135；

**Comment by lurenpluto** [comment]
> When start connection on low resource， tunnel guard may got released for no reference； Fix it on commit [beed213](https://github.com/buckyos/CYFS/commit/beed213555b857235458a30bc741f2df62be95e3)；

You've fixed the panic that occurs in this situation, right? Have you also addressed the various connection errors that occur after stress testing? Is there some potential problem here too
