### ISSUE TITLE
App-manager install DEC APP timesout entered an error state

### ISSUE THREAD

**Issue by lizhihongTest** [buckyos/CYFS#198]
**Describe the bug**
Linux OOD, App-manager install DEC APP timesout entered an error state

**To Reproduce**
+ Setting up a DEC APP installation takes more than 15 minutes
+Install this DEC APP 

Associated questions: #157 

**Expected behavior**
The dec app install preocess was killed after running for 15 minutes. However, the app-manager did not change the status of the DEC APP to InstalledFailed, but continued to execute dec app start.

**System information**
OOD Service : 1.1.0.746-nightly (23-04-10)
System : Linux

**Comment by weiqiushi** [comment]
This is a separate bug, introduced when refactoring the docker api logic

When DecApp executes the install command in the docker container, it forgets to return a timeout error in case of a timeout, and instead returns a successful execution, causing the installation logic to continue down
