### ISSUE TITLE
App-manager doesn't stop install docker container after install timeout

### ISSUE THREAD

**Issue by lizhihongTest** [buckyos/CYFS#203]
**Describe the bug**
App-manager doesn't stop install docker container after install timeout

**To Reproduce**
install dec app: cyfs://5r4MYfFJ7ktzBzSi1sWmU7BJLgpEEdp8ukbWemsFuQc1/9tGpLNnSN39JEAfMzKs1GFCe5GsPhbRXt49fCnL84A6g
```
ubuntu@VM-24-15-ubuntu:/cyfs/log/app-manager$ sudo docker ps 
CONTAINER ID   IMAGE                     COMMAND                  CREATED          STATUS          PORTS     NAMES
83a9a1e5dc54   buckyos/dec-app-base:v1   "/bin/bash /opt/star…"   2 seconds ago    Up 1 second               decapp-9tgplnnsn39jeafmzks1gfce5gsphbrxt49fcnl84a6g
c1958f24d155   buckyos/dec-app-base:v1   "/bin/bash /opt/star…"   15 minutes ago   Up 15 minutes             decapp-9tgplnnsn39jeafmzks1gfce5gsphbrxt49fcnl84a6g-install
514db091dd60   buckyos/dec-app-base:v1   "/bin/bash /opt/star…"   22 hours ago     Up 22 hours               decapp-9tgplnnwtn7n7a4qahmvjrfbksearezhnl4b15ky2opm
```

**Expected behavior**
+ App-manage should stop docker container after install timeout

**System information**
+ 1.1.0.746-nightly (23-04-10)

link issue: https://github.com/buckyos/CYFS/issues/157#issuecomment-1504736806

**Comment by weiqiushi** [comment]
Issue #217 can fix this problem

**Comment by weiqiushi** [comment]
Already fixed in #217, it will be stoppen when next run install command

**Comment by lizhihongTest** [comment]
It will be stoppen when next run install command,But app-manager doesn't stop install docker container after install timeout，This issuse isn`t fixed.

If you think that the installation timeout does not need to close docker container, and  close docker container when user reinstall it, you can close this issuse. 

But I keep my point of view, this way is not the best, why can't the docker container be shut down after the installation timeout?

## Issuse Verification

### Testing Environment

Nighlty ： 1.1.0.753-preview

OOD System : Ubuntu22

dec-app-install-timeout : cyfs://5r4MYfFJ7ktzBzSi1sWmU7BJLgpEEdp8ukbWemsFuQc1/9tGpLNnSN39JEAfMzKs1GFCe5GsPhbRXt49fCnL84A6g


+ 14 minutes after starting the installation
```
CONTAINER ID   IMAGE                     COMMAND                  CREATED          STATUS          PORTS     NAMES
64e54f4f0837   buckyos/dec-app-base:v1   "/bin/bash /opt/star…"   14 minutes ago   Up 14 minutes             decapp-9tgplnnsn39jeafmzks1gfce5gsphbrxt49fcnl84a6g-install
e6c39906d9db   buckyos/dec-app-base:v1   "/bin/bash /opt/star…"   40 hours ago     Up 40 hours               decapp-9tgplnndpfrjuf59sszidvapupd8qnfjusqkh8geny3q
```
+ 15 minutes after starting the installation
```
CONTAINER ID   IMAGE                     COMMAND                  CREATED          STATUS          PORTS     NAMES
64e54f4f0837   buckyos/dec-app-base:v1   "/bin/bash /opt/star…"   15 minutes ago   Up 15 minutes             decapp-9tgplnnsn39jeafmzks1gfce5gsphbrxt49fcnl84a6g-install
e6c39906d9db   buckyos/dec-app-base:v1   "/bin/bash /opt/star…"   40 hours ago     Up 40 hours               decapp-9tgplnndpfrjuf59sszidvapupd8qnfjusqkh8geny3q
```
+ 16 minutes after starting the installation
```
CONTAINER ID   IMAGE                     COMMAND                  CREATED          STATUS          PORTS     NAMES
64e54f4f0837   buckyos/dec-app-base:v1   "/bin/bash /opt/star…"   15 minutes ago   Up 15 minutes             decapp-9tgplnnsn39jeafmzks1gfce5gsphbrxt49fcnl84a6g-install
e6c39906d9db   buckyos/dec-app-base:v1   "/bin/bash /opt/star…"   40 hours ago     Up 40 hours               decapp-9tgplnndpfrjuf59sszidvapupd8qnfjusqkh8geny3q
```
+ Reinstall this dec app
```
CONTAINER ID   IMAGE                     COMMAND                  CREATED         STATUS         PORTS     NAMES  
e1d0fc90ffb6   buckyos/dec-app-base:v1   "/bin/bash /opt/star…"   9 seconds ago   Up 7 seconds             decapp-9tgplnnsn39jeafmzks1gfce5gsphbrxt49fcnl84a6g-install  
e6c39906d9db   buckyos/dec-app-base:v1   "/bin/bash /opt/star…"   40 hours ago    Up 40 hours              decapp-9tgplnndpfrjuf59sszidvapupd8qnfjusqkh8geny3q  
```

**Comment by weiqiushi** [comment]
Yes. I think close previous install container when reinstall app is better way to cover this situation.

Here I follow a principle of goodwill:
- It is presupposed that the DecApp developer's install command is fine, but the install may get stuck due to the user's network, or environmental problems
- The user is presumed to want to use this DecApp, and in case of installation failure, the user prefers to retry the installation rather than uninstall it directly.

Under this premise, killing the previous install container again in the next installation may make the next install end faster. There is no significant degradation effect on the next install compared to killing the container directly

I would close the issue first, but if you find that this causes more problems in some cases, please specify the problem and reopen the issue

@lizhihongTest

**Comment by lizhihongTest** [comment]
@weiqiushi Your description is inaccurate. The next time the user reinstalls, all files of the old DEC APP will be deleted and a new initialization process will be performed. There is no optimization other than stopping the container. On the contrary, in the current implementation, if the user does not operate any more, a container will always run and occupy OOD resources
