### ISSUE TITLE
WIndows App-manager is interrupted and cannot be recovered during the installation of DEC APP npm i

### ISSUE THREAD

**Issue by lizhihongTest** [buckyos/CYFS#207]
**Describe the bug**
WIndows App-manager is interrupted and cannot be recovered during the installation of DEC APP npm i

**To Reproduce**
+ Install cyfs://5r4MYfFJ7ktzBzSi1sWmU7BJLgpEEdp8ukbWemsFuQc1/9tGpLNndpfRjUF59SsZidVaPuPd8QNFJusQKH8genY3Q
+ When DEC APP executes npm i during installation, kill app-manager process
+ Then ood-daamon will restart app-manager.Reinstall dec app will clean up old files, there will be a problem of file occupation
```
[2023-04-13 20:15:19.397449 +08:00] ERROR [ThreadId(32)] [service\app-manager\src\app_controller.rs:154] install app:9tGpLNndpfRjUF59SsZidVaPuPd8QNFJusQKH8genY3Q failed, errio_IOwn(Urk : This file is in use by another program and cannot be accessed by the process. (os error 32), Some(IoError(Os { code: 32, kind: Uncategorized, message: "This file is in use by another program and cannot be accessed by the process." } )))
```
**Expected behavior**
In the process of windows npm i, the file lock created by the system cannot be released, and the user needs to restart the computer to solve this problem. However, similar scenarios will appear during the ood service update process, which needs to be compatible with the update process, or optimized by app-manager. This problem does not exist when app-manager uses docker mode.

**System information**
OOD-Service :  1.1.0.0-nightly (23-04-13) build by code  314d358d

[log.zip](https://github.com/buckyos/CYFS/files/11228594/log.zip)

**Comment by weiqiushi** [comment]
Yes, if AppManager is killed during the install process, it will lose control of the install command process, and if this install command process cannot exit on its own, the above situation will occur

In this case, AppManager cannot automatically restore the environment, and the most practical solution is for the user to restart the machine where OOD is located

**Comment by weiqiushi** [comment]
AppManager does not currently handle this issue.

In some future version, the management of the install logic may be optimized. It may be a overall modification that will work as a new feature

**Comment by weiqiushi** [comment]
The optimization solution proposed in Issue #217 will solve this problem in most scenarios

**Comment by weiqiushi** [comment]
Added a logic to try to kill the previous installation process before installing:

Think about that the install command takes a long time, or if the install command process gets stuck:
- If AppManager is running normally, it will kill the install process after 15 minutes
- If AppManager restarts while waiting, it will retry the installation command after restarting. The previous installation process will be killed at this point

**Comment by lizhihongTest** [comment]
It seems has the same issue compared to before commit

### Testing Environment

Nighlty ： 1.1.0.753-preview

OOD System : Windows10

+ dec-app-service-many-npm-packages cyfs://5r4MYfFJ7ktzBzSi1sWmU7BJLgpEEdp8ukbWemsFuQc1/9tGpLNnPZPoULTFVB6tbzrLkHS564isyc54PmWuNW6DT : DEC APP installation will run "npm i ",Set many npm packages to downloading.

### Verification Step:

+ Install dec app  cyfs://5r4MYfFJ7ktzBzSi1sWmU7BJLgpEEdp8ukbWemsFuQc1/9tGpLNnPZPoULTFVB6tbzrLkHS564isyc54PmWuNW6DT
+ When installation of 9tGpLNnPZPoULTFVB6tbzrLkHS564isyc54PmWuNW6DT is running "npm i" ,kill app-manager process
+ When app-manager auto start , check DEC APP 9tGpLNnPZPoULTFVB6tbzrLkHS564isyc54PmWuNW6DT reinstall result
+ DEC APP 9tGpLNnPZPoULTFVB6tbzrLkHS564isyc54PmWuNW6DT InstallFailed

[app-manager_7880_rCURRENT.log](https://github.com/buckyos/CYFS/files/11303019/app-manager_7880_rCURRENT.log)
[app-manager_9148_rCURRENT.log](https://github.com/buckyos/CYFS/files/11303021/app-manager_9148_rCURRENT.log)

**Comment by weiqiushi** [comment]
Currently, the installation logic of DecApp is as follows:
1. download the files of DecApp to /cyfs/tmp/app
2. Copy the DecApp files to each fixed directory under /cyfs/app
The logic of the above two steps is included in AppPackage.install()
3. After the copy is finished, make sure whether DecApp has service or not. 4.
4. If there is service, execute install command. If there is no service, skip this step.
The logic of the above two steps is included in DApp.install()
5. publish the web folder of decapp
6. write the installation information to the protocol stack, the installation is complete

In the first installation, step 4 will record the pid of the install process and check this pid and kill the previous process the next time you enter step 4.
Whereas in step 2, AppPackage. install() clears the App installation directory, the logic here has no control over the pid information managed by step 4, and if the App installation directory is occupied, it will cause the installation to fail

I may need a redesigned process to solve this problem. it may costs more times then I think.

**Comment by lizhihongTest** [comment]
It has the same issues in #239,but the error is different

**Comment by lizhihongTest** [comment]
Not found fix commit for this issuse. The version 1.1.0.753 has same issue in windows

**Comment by lizhihongTest** [comment]
This issuse hasn`t been fixed .I verified it on version 1.1.0.755, although the log shows that npm i was executed, but the command execution failed, and there is no node_modules file in the disk 
[app-manager_4168_rCURRENT.log](https://github.com/buckyos/CYFS/files/11392748/app-manager_4168_rCURRENT.log)

**Comment by weiqiushi** [comment]
> 

log shows command `npm i` execution failed because of execute timeout after 15 minutes, it started normally, which means that the bug has been fixed

**Comment by lizhihongTest** [comment]
Executing the npm i operation for the second time did not generate the package-lock.json file and any node_modules files. This is probably caused by system factors. Before this operation, the folder operation was deleted and the folder operation was created. It is likely that npm i is operated before deleting the folder

**Comment by weiqiushi** [comment]
> Executing the npm i operation for the second time did not generate the package-lock.json file and any node_modules files. This is probably caused by system factors. Before this operation, the folder operation was deleted and the folder operation was created. It is likely that npm i is operated before deleting the folder

creating node_modules or not may depends on npm logic or your network environment. In any case, this has nothing to do with the bug described in this issue. I think the bug described in this issue has been fixed.

**Comment by lizhihongTest** [comment]
Did you test it?

> 

I manually execute npm i in this directory and it only takes 3 minutes to install it. This is not due to the network.

**Comment by lizhihongTest** [comment]
```
added 1222 packages from 691 contributors in 174.572s

176 packages are looking for funding
```
