### ISSUE TITLE
Reinstall DEC APP mistake clean app log

### ISSUE THREAD

**Issue by lizhihongTest** [buckyos/CYFS#209]
**Describe the bug**
Reinstall DEC APP mistake clean app log

**To Reproduce**
+ When dec app update,reinstall DEC APP will mistake clean app log

**Expected behavior**
The current Uninstall is not atomic，should be split Uninsatll and CleanData

CmdCode::Update just run AppCmd::uninstall、AppCmd::install、AppCmd::start.

CmdCode::Uninstall run AppCmd::uninstall and AppCmd::cleandata.

**System information**
OOD Service : 1.1.0.750

[app-manager.zip](https://github.com/buckyos/CYFS/files/11229967/app-manager.zip)

**Comment by weiqiushi** [comment]
This is not a bug, the current design is similar in that the upgrade and uninstall process retains the data and clean the old log files

**Comment by lizhihongTest** [comment]
I think this is an unacceptable problem: the dec app is updated, but all the logs of the dec app are cleared. For the update process, you can refer to Android overlay installation App

**Comment by weiqiushi** [comment]
In fact, AppManager does **NOT** support the so-called "**upgrade**" and "**overwrite installation**" operations. It only supports the operation of "**modifying the app to a specified version**".

In the current logic, the DecApp data ({cyfs_root}/data/app/{app_id}) folder is kept to give the developer of DecApp a chance to handle the old data of different versions.

The other folders, including log, tmp, and other folders not listed, are considered by the AppManager as data that "does not affect the normal work of DecApp" and are deleted by the AppManager at certain points in time.
In the current logic, the non-data folder will be cleared when the app is uninstalled or migrated to a specific version. This is because AppManager thinks that there is some "version-specific temporary data" stored here, which is no longer relevant after switching versions.

**Comment by lizhihongTest** [comment]
Generally, clearing log files or temporary cache files is controlled by the time dimension, such as only caching for one month. When the update interval may be one day or one hour, during the software development process, it is very common to perform service upgrades and check the logs before and after the upgrade.

**Comment by lizhihongTest** [comment]
Why is your design to clear the log when the dec-app is updated? For developers, the log before the update is meaningless? I do not think so. I have never seen a similar development framework agreement that deletes the old log files of the service when the service is released.If you must design like this, then I just can believe your design philosophy is good.

**Comment by weiqiushi** [comment]
During daily operation, it is usually pointless to look at the logs of non-current version output.
The general workflow is: -> Release -> Update -> Run -> Errors -> Analyze error logs -> Modify bugs -> Release new version, in this workflow, it is not necessary to check the logs of the old version residuals

If the process involves installing a new version and upgrading the old data, the upgrade operation also happens on the new code, and normally you only need to pay attention to the logs of the new version.

In my development experience, there is no scenario where I still need to pay attention to the legacy logs of the old version after upgrading

If you have encountered such a scenario, please feel free to discuss further in your reply

**Comment by weiqiushi** [comment]
> Generally, clearing log files or temporary cache files is controlled by the time dimension, such as only caching for one month. When the update interval may be one day or one hour, during the software development process, it is very common to perform service upgrades and check the logs before and after the upgrade.

Rather, on the normal **user** system, logs are usually rolling and capacity-dependent. Anything that exceeds capacity is usually discarded immediately. When clearing logs manually, there is usually only one operation, "clear all".

The scenario you describe is usually found on a server system where the user knows the system well, has full operational rights, and is responsible for the services running on the system. In this case, some customized, more granular log management policies are used

The OOD system is more like windows, the user of OOD can be analogous to a windows user, while the developer of DecApp is similar to the developer of windows software, who usually has no relationship with the OOD user.

From this point of view, AppManager is designed to focus more on protecting the stability of the OOD system and other experiences of OOD users when a DecApp behaves unstably or even maliciously.
