### ISSUE TITLE
v82 testing

### ISSUE THREAD

**Issue by tracy101** [buckyos/CYFS#211]
Issue for v82 testing. Please help testing on a variety of supported platforms, as well as interaction with different software.

Let us know which version you tested on which operating system.

If you find an issue, please search Github for known issues first and then open a new Github issue.

This issue should not be used to report bugs, as a single thread makes it impossible to track more than one topic.

### **What to test**
For an idea what to test, see  [82 release candidate testing guide](https://github.com/buckyos/CYFS/wiki/82-Release-Candidate-Testing-Guide)

**Comment by lizhihongTest** [comment]
I build cyfs stack and bdt tools. we can download by  http://bdttest.tinyappcloud.com/cyfs_test_package/v1.1.1.81/

**Comment by lizhihongTest** [comment]
I conducted a regression test on CYFS SATCK NDN ,  and the detailed test report can be found in:  http://bdttest.tinyappcloud.com/cyfs_test_package/v1.1.1.81/cyfs_stack_ndn/mochawesome-report/mochawesome.html

**Comment by lizhihongTest** [comment]
I conducted a regression test on CYFS SATCK Trans , and the detailed test report can be found in: http://bdttest.tinyappcloud.com/cyfs_test_package/v1.1.1.81/cyfs_stack_trans/mochawesome-report/mochawesome.html

**Comment by lizhihongTest** [comment]
I conducted a regression test on CYFS BDT protocol , and the detailed test report can be found in: http://bdttest.tinyappcloud.com/cyfs_test_package/v1.1.1.81/bdt_report/TestcaseReport.html

**Comment by lizhihongTest** [comment]
I create a DEC APP in the beat environment, you can use the following DEC APP for testing:

+ only web type
cyfs://5r4MYfFYqjgMTa4JdYC4L87w6w4jUrQ1nUhYJ3AjcgfC/9tGpLNnictgciVGsrtcnR3UgQ3h66hueV9QtQhkspGPy

+ only service type
cyfs://5r4MYfFYqjgMTa4JdYC4L87w6w4jUrQ1nUhYJ3AjcgfC/9tGpLNngXQbEePgnuizTGoshmGkBowjmGcG54TEJBCyM

+ service error type
cyfs://5r4MYfFYqjgMTa4JdYC4L87w6w4jUrQ1nUhYJ3AjcgfC/9tGpLNnUXCvJVTn6fev1meq7WraqkH8wHLR5KRgWghPV

+ executable service type
cyfs://5r4MYfFYqjgMTa4JdYC4L87w6w4jUrQ1nUhYJ3AjcgfC/9tGpLNnQnEzYwvioj9FGbmmpFJy15wxQmBsDBxWbwiKX

+ service + web type
cyfs://5r4MYfFYqjgMTa4JdYC4L87w6w4jUrQ1nUhYJ3AjcgfC/9tGpLNni9AYycMDC9LrAAKoPqQc7VQSnodotFWXuh5D1

+ rust dec app
cyfs://5r4MYfFYqjgMTa4JdYC4L87w6w4jUrQ1nUhYJ3AjcgfC/9tGpLNnHAp2vgMR5BcwVf4HWiELkP71JXWqRwED8Pvpn

**Comment by Revelee-art** [comment]
Tested cyfs-tool-beta, this version has not changed it, only check the main functions of cyfs-tool after cyfs stack update, including the following content:

- Test the tool's desc command to activate the cyfs browser and wallet or cyber-chat
- Test cyfs meta's transfer, cash withdrawal, and check balance functions
- Test the identity import function of cyber-chat or wallet
- Test dec app project creation and release

cyfs-tool v0.6.3

**Comment by Mikestar01** [comment]
I have tested the functions provided by Cyber Chat including as followings：
- binding and activating ood(windows)  
- activating CYFS Browser(windows)  
- Operating DecApps(rust or node version) such as stop/run/install/uninstall
- Reset DID
- Add backup OOD
- Switch OOD
- Delete OOD
the  tested version of Cyber Chat:  Android 1.0.49（beta） IOS 1.0.38（beta）
all pass except the problem as below: 
- after switching OOD, I coudn't stop the all the Dec App， get the prompt of “Can not stop app. app status not found in list“

**Comment by weiqiushi** [comment]
> I have tested the functions provided by Cyber Chat including as followings：
> 
> * Binding and activating ood(windows)
> * Activating CYFS Browser(windows)
> * Operating DecApps(rust or node version) such as stop/run/install/uninstall
> * Reset DID
> * Add backup OOD
> * Switch OOD
> * Delete OOD
>   the  tested version of Cyber Chat:  Android 1.0.49（beta） IOS 1.0.38（beta）
>   All pass except the problem as below:
> * After switching OOD, I coudn't stop all the Dec App， get the prompt of “Can not stop app. app status not found in list“ [After switching OOD  stop Dec App get prompt of “Can not stop app. app status not found in list“ #222](https://github.com/buckyos/CYFS/issues/222)

After analysis, this is a timing problem when switching active OOD, and the probability of occurrence is low. I judge that it does not affect this version release

**Comment by tracy101** [comment]
> > I have tested the functions provided by Cyber Chat including as followings：
> > 
> > * Binding and activating ood(windows)
> > * Activating CYFS Browser(windows)
> > * Operating DecApps(rust or node version) such as stop/run/install/uninstall
> > * Reset DID
> > * Add backup OOD
> > * Switch OOD
> > * Delete OOD
> >   the  tested version of Cyber Chat:  Android 1.0.49（beta） IOS 1.0.38（beta）
> >   All pass except the problem as below:
> > * After switching OOD, I coudn't stop all the Dec App， get the prompt of “Can not stop app. app status not found in list“ [After switching OOD  stop Dec App get prompt of “Can not stop app. app status not found in list“ #222](https://github.com/buckyos/CYFS/issues/222)
> 
> After analysis, this is a timing problem when switching active OOD, and the probability of occurrence is low. I judge that it does not affect this version release

After restart the service of the app manager in OOD , the prompt is disappeared，and the process of stop Dec App is normal。
