### ISSUE TITLE
When start dec app service error ,app-manger auto retry 4 times

### ISSUE THREAD

**Issue by lizhihongTest** [buckyos/CYFS#212]
**Describe the bug**
When start dec app service error ,app-manger auto retry 4 times. And it took me 5 minutes to find out that the startup failed, which is an ineffective retry mechanism and delays the time when the error is thrown
**To Reproduce**
+ Install cyfs://5r4MYfFJ7ktzBzSi1sWmU7BJLgpEEdp8ukbWemsFuQc1/9tGpLNnYJZrs4woomnUf3QoadQgZQV6HjwoN5WPUpjH5
+ The dec app  service start will auto exit
```
Line 1033: [2023-04-14 19:29:41.894949 +08:00] INFO [ThreadId(26)] [service\app-manager\src\app_manager_ex.rs:660] [RUNNING CHECK] app status is running, but not actually. will restart it, app:9tGpLNnYJZrs4woomnUf3QoadQgZQV6HjwoN5WPUpjH5, retry count:1
Line 1185: [2023-04-14 19:30:41.896231 +08:00] INFO [ThreadId(35)] [service\app-manager\src\app_manager_ex.rs:660] [RUNNING CHECK] app status is running, but not actually. will restart it, app:9tGpLNnYJZrs4woomnUf3QoadQgZQV6HjwoN5WPUpjH5, retry count:2
Line 1337: [2023-04-14 19:31:41.896965 +08:00] INFO [ThreadId(28)] [service\app-manager\src\app_manager_ex.rs:660] [RUNNING CHECK] app status is running, but not actually. will restart it, app:9tGpLNnYJZrs4woomnUf3QoadQgZQV6HjwoN5WPUpjH5, retry count:3
Line 1489: [2023-04-14 19:32:41.897399 +08:00] INFO [ThreadId(23)] [service\app-manager\src\app_manager_ex.rs:660] [RUNNING CHECK] app status is running, but not actually. will restart it, app:9tGpLNnYJZrs4woomnUf3QoadQgZQV6HjwoN5WPUpjH5, retry count:4
Line 1653: [2023-04-14 19:33:41.898762 +08:00] INFO [ThreadId(28)] [service\app-manager\src\app_manager_ex.rs:654] [RUNNING CHECK] app failed count is out of limit! app:9tGpLNnYJZrs4woomnUf3QoadQgZQV6HjwoN5WPUpjH5, change app status from [Running] to [RunException]

```
**Expected behavior**
The retry mechanism is only used to recover from system abnormal interruption, not to increase retry in the normal process. This retry has no practical significance and will only increase the burden for users.

**System information**
OOD Service :
[app-manager_31752_rCURRENT.log](https://github.com/buckyos/CYFS/files/11232634/app-manager_31752_rCURRENT.log)
 1.0.1.750

**Comment by weiqiushi** [comment]
This is a useful logic because AppManager uses periodic detection after starting a DecApp Service to determine whether this Service is started successfully. If the start-up is judged as failed for N times in a row, this App is judged as RunException and no more attempts are made to start the Service.

This N value is part of the internal logic of AppManager, and the current N value is 5. DecApp developers should not be concerned about the specific value of this N value, but only need to know the logic of this decision.

**Comment by weiqiushi** [comment]
This N value is part of the internal logic of AppManager, and the current N value is 5. DecApp developers should not be concerned about the specific value of this N value, but only need to know the logic of this decision.

**Comment by lurenpluto** [comment]
It seems to be related to the description of "retry count" in #213
