### ISSUE TITLE
Error of op-env usage in zone manager

### ISSUE THREAD

**Issue by lurenpluto** [buckyos/CYFS#224]
In the process of analyzing some logs, I found that in the process of using op-env to operate global-state, there are cases where op-env is not used for a long time and is accidentally recycled:

<details><summary>Details</summary>
<p>

[2023-04-18 15:24:08.904666 +08:00] INFO [ThreadId(3)] [component\cyfs-stack\src\zone\zone_container.rs:344] remove zone: zone_id=9cfBkPstTuMstxZwApvSpv1jrU6pkAqEJRX5MHDQjSzm, owner=5r4MYfFSiJ7FhxjaYqDiFwZK6RgNr7HRLHnpj6KXmYkY
[2023-04-18 15:24:08.904703 +08:00] ERROR [ThreadId(3)] [component\cyfs-base\src\objects\object_map\op_env.rs:420] op_env not found! sid=4611787511985883458
[2023-04-18 15:24:08.904722 +08:00] ERROR [ThreadId(3)] [component\cyfs-stack\src\zone\zone_container.rs:449] remove zone from global state failed! zone=9cfBkPstTuMstxZwApvSpv1jrU6pkAqEJRX5MHDQjSzm, err: (NotFound, op_env not found! sid=4611787511985883458, None)

</p>
</details> 

The above is part of the log output from cyfs-stack's zone manager, which shows that the internal op-env has not been operated for a long time, resulting in a gc, and subsequent operations on the global-state have failed

**Comment by lurenpluto** [comment]
Some background knowledge on this issue:

Now there are two types of op-env
- Natvie(unmanaged)
This op-env is fully managed by the caller, and the op-env-manager is not managed, so there is no lifecycle or leakage problem.
	
- Managed
Each op-env is assigned an id, and the caller uses op-env-stub to make the call; when it is finished, it calls commit or abort, and the corresponding op-env is managed by op-env-manager.
	
	Here a problem will arise, that is, if the op-env creator forgets to call abort or commit, then it will lead to more and more op-env managed by op-env-manager, which will lead to memory leak

So in order to solve the problem of leaking managed op-env, op-env-manager adds a gc mechanism, which means that op-env that have been inactive for a long time (calling any interface is considered active) will be recycled periodically, and this time interval is now as follows:(in microseconds)

https://github.com/buckyos/CYFS/blob/580816c558304f941fce35f891ad77aee928a71b/src/component/cyfs-base/src/objects/object_map/op_env.rs#L286

The kernel gc logic as follows:
https://github.com/buckyos/CYFS/blob/580816c558304f941fce35f891ad77aee928a71b/src/component/cyfs-base/src/objects/object_map/op_env.rs#L365-L378

**Comment by lurenpluto** [comment]
As the zone manager is an indirectly used global-state based collection to manage zones, the entire structure hierarchy is roughly as follows

![zone manager cache](https://user-images.githubusercontent.com/3624316/232967096-a58aceb0-35b1-4b89-9465-35150f497f2d.png)

So two solutions are considered now:

1. add a keep alive mechanism
	This is the easiest and fastest one, adding a timed method call to avoid the associated op-env being gc
	
2. provide the implementation of OpEnvStub based on the native op-env
	Currently, StateStorage directly uses `PathOpEnvStub` and `SingleOpEnvStub` to operate the managed op-env, which is transferred to the global-state native processor through the transform layer, so basically it is still used as an "external module "perspective to use op-env to operate global-state
	
	So this can be considered to improvethe native `OpEnvStub` implementation, but the complexity is relatively high, may involve some type definition changes

So now first through mode 1, to circumvent this problem; mode 2 implementation can be subsequently discussed to expand

**Comment by lurenpluto** [comment]
The keep alive mechanism has been added to StateStorage to ensure that long periods of inactivity do not result in the inability to write data because the op-env is gc.

See at 511d6c134c163ef6cc7f1ffd497adc41f85bf8f8

The test method can be based on the known problem of zone-manager, after the OOD is started and left idle for a period of time (at least an hour), then switch the active-standby OOD, which will cause the current zone information to change, and then see if the logs still have the above error

**Comment by lizhihongTest** [comment]
cyfs-stack's zone manager op-env will not recycled by gc in Nighlty 1.1.0.756
[gateway_1566334_rCURRENT.log](https://github.com/buckyos/CYFS/files/11411146/gateway_1566334_rCURRENT.log)

**Comment by lizhihongTest** [comment]
From the following logs, it can be found that zone_container can operate op-env after one hour
```
Line 2507: [2023-05-06 11:56:51.448027 +08:00] INFO [ThreadId(4)] [component/cyfs-stack/src/zone/zone_container.rs:344] remove zone: zone_id=9cfBkPt1Z111JSi9JRucHmDESBm8r5F6SHoUUYaXTKS4, owner=5r4MYfFQ1BcMPzkS4qPtUX69kYDXUU5iPbQpd62tEZ9N
Line 2508: [2023-05-06 11:56:51.448084 +08:00] INFO [ThreadId(4)] [component/cyfs-stack/src/zone/zone_container.rs:454] remove zone from global state success! zone=9cfBkPt1Z111JSi9JRucHmDESBm8r5F6SHoUUYaXTKS4
Line 2511: [2023-05-06 11:56:51.454200 +08:00] INFO [ThreadId(4)] [component/cyfs-stack/src/zone/zone_container.rs:466] delete zone from noc success! zone=9cfBkPt1Z111JSi9JRucHmDESBm8r5F6SHoUUYaXTKS4
Line 2514: [2023-05-06 11:56:51.454291 +08:00] WARN [ThreadId(4)] [component/cyfs-stack/src/zone/zone_container.rs:309] get zone by device but not exists! device=5aSixgMF35SkoNeDm2J5uckyUdJDDXeRD6inHvuF6ACu, zone=9cfBkPt1Z111JSi9JRucHmDESBm8r5F6SHoUUYaXTKS4
Line 2523: [2023-05-06 11:56:51.461541 +08:00] INFO [ThreadId(4)] [component/cyfs-stack/src/zone/zone_container.rs:174] will create new zone for owner=5r4MYfFQ1BcMPzkS4qPtUX69kYDXUU5iPbQpd62tEZ9N, device=Some(5aSixgMF35SkoNeDm2J5uckyUdJDDXeRD6inHvuF6ACu), zone=9cfBkPt1Z111JSi9JRucHmDESBm8r5F6SHoUUYaXTKS4, known_device_list=[5aSixgPNVDrywHZt9Vka9v9ZZZwiTd4Ktss22WkJ8ngo]
Line 2524: [2023-05-06 11:56:51.461606 +08:00] WARN [ThreadId(4)] [component/cyfs-stack/src/zone/zone_container.rs:95] will replace device->zone: 5aSixgLox5CRLLaMcnsRz75A4khSXay5WRjfN5VjNNVx, zone 9cfBkPt1Z111JSi9JRucHmDESBm8r5F6SHoUUYaXTKS4->9cfBkPt1Z111JSi9JRucHmDESBm8r5F6SHoUUYaXTKS4
Line 2525: [2023-05-06 11:56:51.461645 +08:00] WARN [ThreadId(4)] [component/cyfs-stack/src/zone/zone_container.rs:95] will replace device->zone: 5aSixgMF35SkoNeDm2J5uckyUdJDDXeRD6inHvuF6ACu, zone 9cfBkPt1Z111JSi9JRucHmDESBm8r5F6SHoUUYaXTKS4->9cfBkPt1Z111JSi9JRucHmDESBm8r5F6SHoUUYaXTKS4
Line 2526: [2023-05-06 11:56:51.461681 +08:00] WARN [ThreadId(4)] [component/cyfs-stack/src/zone/zone_container.rs:95] will replace device->zone: 5aSixgPNVDrywHZt9Vka9v9ZZZwiTd4Ktss22WkJ8ngo, zone 9cfBkPt1Z111JSi9JRucHmDESBm8r5F6SHoUUYaXTKS4->9cfBkPt1Z111JSi9JRucHmDESBm8r5F6SHoUUYaXTKS4
Line 2527: [2023-05-06 11:56:51.461740 +08:00] INFO [ThreadId(4)] [component/cyfs-stack/src/zone/zone_container.rs:396] insert zone to global state success! zone=9cfBkPt1Z111JSi9JRucHmDESBm8r5F6SHoUUYaXTKS4
Line 2530: [2023-05-06 11:56:51.469529 +08:00] INFO [ThreadId(5)] [component/cyfs-stack/src/zone/zone_container.rs:429] insert zone to noc success! zone=9cfBkPt1Z111JSi9JRucHmDESBm8r5F6SHoUUYaXTKS4
```
[gateway_1566334_rCURRENT.log](https://github.com/buckyos/CYFS/files/11411234/gateway_1566334_rCURRENT.log)

[gateway_1566334_r00003.log](https://github.com/buckyos/CYFS/files/11411235/gateway_1566334_r00003.log)

**Comment by lurenpluto** [comment]
> From the following logs, it can be found that zone_container can operate op-env after one hour
> 
> ```
> Line 2507: [2023-05-06 11:56:51.448027 +08:00] INFO [ThreadId(4)] [component/cyfs-stack/src/zone/zone_container.rs:344] remove zone: zone_id=9cfBkPt1Z111JSi9JRucHmDESBm8r5F6SHoUUYaXTKS4, owner=5r4MYfFQ1BcMPzkS4qPtUX69kYDXUU5iPbQpd62tEZ9N
> Line 2508: [2023-05-06 11:56:51.448084 +08:00] INFO [ThreadId(4)] [component/cyfs-stack/src/zone/zone_container.rs:454] remove zone from global state success! zone=9cfBkPt1Z111JSi9JRucHmDESBm8r5F6SHoUUYaXTKS4
> Line 2511: [2023-05-06 11:56:51.454200 +08:00] INFO [ThreadId(4)] [component/cyfs-stack/src/zone/zone_container.rs:466] delete zone from noc success! zone=9cfBkPt1Z111JSi9JRucHmDESBm8r5F6SHoUUYaXTKS4
> Line 2514: [2023-05-06 11:56:51.454291 +08:00] WARN [ThreadId(4)] [component/cyfs-stack/src/zone/zone_container.rs:309] get zone by device but not exists! device=5aSixgMF35SkoNeDm2J5uckyUdJDDXeRD6inHvuF6ACu, zone=9cfBkPt1Z111JSi9JRucHmDESBm8r5F6SHoUUYaXTKS4
> Line 2523: [2023-05-06 11:56:51.461541 +08:00] INFO [ThreadId(4)] [component/cyfs-stack/src/zone/zone_container.rs:174] will create new zone for owner=5r4MYfFQ1BcMPzkS4qPtUX69kYDXUU5iPbQpd62tEZ9N, device=Some(5aSixgMF35SkoNeDm2J5uckyUdJDDXeRD6inHvuF6ACu), zone=9cfBkPt1Z111JSi9JRucHmDESBm8r5F6SHoUUYaXTKS4, known_device_list=[5aSixgPNVDrywHZt9Vka9v9ZZZwiTd4Ktss22WkJ8ngo]
> Line 2524: [2023-05-06 11:56:51.461606 +08:00] WARN [ThreadId(4)] [component/cyfs-stack/src/zone/zone_container.rs:95] will replace device->zone: 5aSixgLox5CRLLaMcnsRz75A4khSXay5WRjfN5VjNNVx, zone 9cfBkPt1Z111JSi9JRucHmDESBm8r5F6SHoUUYaXTKS4->9cfBkPt1Z111JSi9JRucHmDESBm8r5F6SHoUUYaXTKS4
> Line 2525: [2023-05-06 11:56:51.461645 +08:00] WARN [ThreadId(4)] [component/cyfs-stack/src/zone/zone_container.rs:95] will replace device->zone: 5aSixgMF35SkoNeDm2J5uckyUdJDDXeRD6inHvuF6ACu, zone 9cfBkPt1Z111JSi9JRucHmDESBm8r5F6SHoUUYaXTKS4->9cfBkPt1Z111JSi9JRucHmDESBm8r5F6SHoUUYaXTKS4
> Line 2526: [2023-05-06 11:56:51.461681 +08:00] WARN [ThreadId(4)] [component/cyfs-stack/src/zone/zone_container.rs:95] will replace device->zone: 5aSixgPNVDrywHZt9Vka9v9ZZZwiTd4Ktss22WkJ8ngo, zone 9cfBkPt1Z111JSi9JRucHmDESBm8r5F6SHoUUYaXTKS4->9cfBkPt1Z111JSi9JRucHmDESBm8r5F6SHoUUYaXTKS4
> Line 2527: [2023-05-06 11:56:51.461740 +08:00] INFO [ThreadId(4)] [component/cyfs-stack/src/zone/zone_container.rs:396] insert zone to global state success! zone=9cfBkPt1Z111JSi9JRucHmDESBm8r5F6SHoUUYaXTKS4
> Line 2530: [2023-05-06 11:56:51.469529 +08:00] INFO [ThreadId(5)] [component/cyfs-stack/src/zone/zone_container.rs:429] insert zone to noc success! zone=9cfBkPt1Z111JSi9JRucHmDESBm8r5F6SHoUUYaXTKS4
> ```
> 
> [gateway_1566334_rCURRENT.log](https://github.com/buckyos/CYFS/files/11411234/gateway_1566334_rCURRENT.log)
> 
> [gateway_1566334_r00003.log](https://github.com/buckyos/CYFS/files/11411235/gateway_1566334_r00003.log)

This feature seems to be working properly, if there are any other problems again welcome feedback!
