### ISSUE TITLE
Test schedule for 83 Release

### ISSUE THREAD

**Issue by lizhihongTest** [buckyos/CYFS#227]
Issue for v83 testing. Please help testing on a variety of supported platforms, as well as interaction with different software.

Let us know which version you tested on which operating system.

If you find an issue, please search Github for known issues first and then open a new Github issue.

This issue should not be used to report bugs, as a single thread makes it impossible to track more than one topic.

Add test task:
+ Feature:
- [x]  #228
- [x]  [Add dynamic acl related support #18](https://github.com/buckyos/cyfs-ts-sdk/issues/18)
- [x]  #175
- [x]  #217 
+ Bug fixed:
- [x]  #203
- [x]  #216 
- [x]  #222 
- [x]  #224
- [x]  #238 
- [x]  #207
- [x]  #239
- [x]  #247
- [x]  #214
+ Other panic fixed

These code modifications have been released in Nighlty version 1.1.0.753-1.1.0.756, and the test version specified by the configuration can be referred to:[How to config OOD service testing environment](https://github.com/buckyos/cyfs-test-lab/blob/main/doc/en/tutorial/Test-Environment/ood_sevice_config_version.md)

**Comment by lizhihongTest** [comment]
Add test task: #203

**Comment by lizhihongTest** [comment]
Add test task: #207

**Comment by lizhihongTest** [comment]
Add test task: #217

**Comment by lizhihongTest** [comment]
Add test task: #216

**Comment by lizhihongTest** [comment]
Add test task: #222

**Comment by lizhihongTest** [comment]
Add test task: #224

**Comment by weiqiushi** [comment]
@lizhihongTest I think you can use a task list to trace these test task, like:
- [ ] Issue #203
- [ ] Issue #207
- [ ] Issue #222

And you can edit your first issue content when you add a new test task

**Comment by lizhihongTest** [comment]
Add test task:
+ #203 
+ #207
+ #216 
+ #217 
+ #222 
+ #224

These code modifications have been released in Nighlty version 1.1.0.753, and the test version specified by the configuration can be referred to:[How to config OOD service testing environment](https://github.com/buckyos/cyfs-test-lab/blob/main/doc/en/tutorial/Test-Environment/ood_sevice_config_version.md)

**Comment by lizhihongTest** [comment]
The progress and record details of the CYFS Stack & Service test will be uploaded to [Release_83_#227](https://github.com/buckyos/cyfs-test-lab/blob/main/doc/en/TestProgress/Release_83_%23227/CYFS_Stack%26Service.md)

**Comment by lizhihongTest** [comment]
BDT protocol stack version V83 has completed regression testing ： http://bdttest.tinyappcloud.com/cyfs_test_package/v1.1.1.83/bdt_report/TestcaseReport.html

**Comment by lizhihongTest** [comment]
cyfs-test-lab test dec app has update cyfs-sdk@0.6.3

**Comment by lizhihongTest** [comment]
@weiqiushi Only web dec_app install failed #257 ,This issuse should fixed in this release version.

**Comment by lizhihongTest** [comment]
CYFS Stack NDN/Trans version V83 has completed regression testing ：
+ NDN: http://bdttest.tinyappcloud.com/cyfs_test_package/v1.1.1.83/cyfs_stack/V83_cyfs_stack_ndn/
+ Trans: http://bdttest.tinyappcloud.com/cyfs_test_package/v1.1.1.83/cyfs_stack/V83_cyfs_stack_trans/

**Comment by Revelee-art** [comment]
Tested cyfs-tool-beta, this version has not changed it, only check the main functions of cyfs-tool after cyfs stack update, including the following content:

Test the tool's desc command to activate the cyfs browser and wallet or cyber-chat
Test cyfs meta's transfer, cash withdrawal, and check balance functions
Test the identity import function of cyber-chat or wallet
Test dec app project creation and release
The above content is passed in version 0.6.3

**Comment by Xiongdan007** [comment]
I mainly test the content related to CYFS Browser, including the following:

Basic environment: linux ood+cyberchat android version+Windows version CYFS Browser and Mac version CYFS Browser;

Windows version CYFS Browser built -in function;

MAC version of CYFS Browser built -in function.

The above content is passed in linux ood version 1.1.1.83+cyberchat android version 1.0.49+CYFS Browser Windows version 1.0.1.117 and CYFS Browser Mac version 1.0.1.112.
