### ISSUE TITLE
Linux app-manager restore installation failed when app-manager breaks down when DEC APP is running "npm i"

### ISSUE THREAD

**Issue by lizhihongTest** [buckyos/CYFS#239]
**Describe the bug**
Linux app-manager restore installation failed when app-manager breaks down when DEC APP is running "npm i"

**To Reproduce**
+ Install dec-app-service-many-npm-packages cyfs://5r4MYfFJ7ktzBzSi1sWmU7BJLgpEEdp8ukbWemsFuQc1/9tGpLNnPZPoULTFVB6tbzrLkHS564isyc54PmWuNW6DT
+ When DEC APP is running "npm i", kill the app-manager process
+ When the app-manager is restarted by ood-daemon,Check the result of this app`status.

**Expected behavior**
The app-manager will reinstall 9tGpLNnPZPoULTFVB6tbzrLkHS564isyc54PmWuNW6DT and Installfailed 

**System information**
Nighlty ： 1.1.0.753-preview
OOD System : cyfs-test-lab::PC-0005(Ubuntu22)

[app-manager_267347_rCURRENT.log](https://github.com/buckyos/CYFS/files/11303308/app-manager_267347_rCURRENT.log)

[app-manager_261428_rCURRENT.log](https://github.com/buckyos/CYFS/files/11303309/app-manager_261428_rCURRENT.log)

**Comment by weiqiushi** [comment]
The cause of this problem is different from #207, the direct cause is that for some reason the docker startup script does not exist when starting docker, resulting in an error executing the install command in docker

The root cause of this problem is not yet clear and requires further testing

**Comment by lurenpluto** [comment]
Here's a question: If a dec app is installed and the app-manager process quits or restarts for some reason, what happens to the old installation process? Will it quit or will it continue? Does the new app-manager process clean up the old installation process and retrigger the installation after it starts?

**Comment by weiqiushi** [comment]
> Here's a question: If a dec app is installed and the app-manager process quits or restarts for some reason, what happens to the old installation process? Will it quit or will it continue? Does the new app-manager process clean up the old installation process and retrigger the installation after it starts?

Testing has shown that if app-manager exits during the execution of the install command, the install process usually continues to exist:
- On Windows, app-manager exits without affecting the child processes, and the install process exist
- On Linux, app-manager start the installation in docker, the app-manager kills the docker run process when it exits, but the docker container exist

Under the new logic of app-manager, when app-manager restarts, it will start the installation logic again. In this installation logic, the previously started installation process or the container was be killed.
