### ISSUE TITLE
App-Manager support for OOD standby mode

### ISSUE THREAD

**Issue by lurenpluto** [buckyos/CYFS#24]
In the standby mode of OOD, App-Manager should not start the app service, and should not modify the root-state (because it is read-only mode), and when the OOD working mode is switched, all app services need to be stopped

A more concise solution is that when the mode is switched, the OOD-daemon is responsible for stopping the App-Manager, and the App-Manager needs to stop all currently running app services under the --stop command.

**Comment by glen0125** [comment]
#[580e334](https://github.com/buckyos/CYFS/commit/580e334bb8fd246948b21ad86331c6df50847e41) Fix this issue.
