### ISSUE TITLE
How to config handler`s filter?

### ISSUE THREAD

**Issue by lizhihongTest** [buckyos/CYFS#246]
If I want to use stack.router_handlers().add_handler() to register an event, how do I set the filter? There is currently no document found about filter rules

**Comment by weiqiushi** [comment]
The filter is part of the old processing logic of the protocol stack, and is used to distribute requests to different handlers.  
Currently recommended use req_path to distribute between different handlers, and the filter field should be left empty.

**Comment by lurenpluto** [comment]
> If I want to use stack.router_handlers().add_handler() to register an event, how do I set the filter? There is currently no document found about filter rules

The dynamic acl handler supports two types of filters, string and blob, and the corresponding usage methods can be found in the above document.

For the introduction and usage of glob, please refer to https://docs.rs/globset/latest/globset/#syntax
