### ISSUE TITLE
The parameters of A link should be maintained after transform.

### ISSUE THREAD

**Issue by jinquantianxia** [buckyos/CYFS#34]
**Describe the bug**
The parameters will be removed when I open an A link  html file.

**To Reproduce**
For example, I will open the following link:
cyfs://a/9tGpLNna8UVtPYCfV1LbRN2Bqa5G9vRBKhDhZiWjd7wA/index.html?hello=world
once I open it, the link where transform to like this :
http://127.0.0.1:38090/o/5hLXAcNtoFKLkvPEmdMFDJ9NjpCWJxdSZU6uKXPkR6m9/95RvaS5cWCTCKejHojmHtauJTQwL7FZ1AMeLLba1Dk1w/index.html?dec_id=9tGpLNna8UVtPYCfV1LbRN2Bqa5G9vRBKhDhZiWjd7wA
which means I've lost my parameter.

**Expected behavior**
In fact, the result should be like this:
http://127.0.0.1:38090/o/5hLXAcNtoFKLkvPEmdMFDJ9NjpCWJxdSZU6uKXPkR6m9/95RvaS5cWCTCKejHojmHtauJTQwL7FZ1AMeLLba1Dk1w/index.html?dec_id=9tGpLNna8UVtPYCfV1LbRN2Bqa5G9vRBKhDhZiWjd7wA?hello=world

**Comment by lurenpluto** [comment]
Added corresponding support into current beta version. It should be noted that the query parameter name cannot conflict with the built-in parameter name, otherwise it will not be passed.

# 48d1d25f20f7431e469bf14ff00c8a9aa246de98
