### ISSUE TITLE
Window ood-installer 重新启动导致的gateway.toml被覆盖的bug

### ISSUE THREAD

**Issue by yangjunying** [buckyos/CYFS#36]
**Describe the bug**

 CYFSOOD-x86-64-1.0.0.505-nightly安装包。WIN10专业版，安装配置完成后，再次重新启动机器，不能正确启动服务导致CYFS_browser中，info不能正确的显示OOD的信息。同时会每隔30秒启动一次服务（应该是cyfs-drive-server.exe）
**To Reproduce**

1，确保本机没有安装mogodb
2，下载 diy-ood-window版CYFSOOD-x86-64-1.0.0.505-nightly安装包，安装
3，使用https://youtrack.buckycloud.com/articles/SHARES-A-2/CYFS开发环境搭建 （注意host修改）中提供的 cyfs身份创建工具 中的，gateway.toml，替换 c:\cyfs\etc\gateway\gateway.toml 这个文件。此文件中，数据库配置为sqlite
4，关联账号
5，打开browser，可以看到ood的info信息是正确的
6，关机重新启动，ood-installer 又被自动执行。
7，c:\cyfs\etc\gateway\gateway.toml 这个文件被重新覆盖，其中的数据库配置又被修改为mongodb。
8，启动browser，不能正确显示ood 信息，同时会不停的启动某个服务（一闪而过）。

**Expected behavior**

再次重启启动，运行ood-installer ，不应该覆盖被修改的配置文件
**System information**

ftp 服务上下载 的CYFSOOD-x86-64-1.0.0.505-nightly安装包

OS：win10

**Additional context**

**Comment by weiqiushi** [comment]
Already fixed after intaller version 1.0.0.511
