### ISSUE TITLE
Need ood-daemon-stop.sh on DIYOOD 

### ISSUE THREAD

**Issue by waterflier** [buckyos/CYFS#48]
**The purpose of the feature**
I want stop the ood service and backup the /cyfs/data/, now I killed service process manually

**Describe the solutions to the feature you'd like**
I need start/stop scripts~

**Comment by alexsunxl** [comment]
#59   consider using systemd  to control the ood-daemon scripts

```systemctl start ood-daemon```

```systemctl stop ood-daemon```

**Comment by lurenpluto** [comment]
Now add stop_all support to stop all the services for ood-daemon, all cyfs services and apps including ood-daemon itself can be stopped by the command:

First find the ood-daemon exe on your ood's cyfs root dir, then exec:
```
{cyfs}/services/current/bin/ood-daemon --stop_all
```
