### ISSUE TITLE
PeopleObject's public key can be replaced？

### ISSUE THREAD

**Issue by waterflier** [buckyos/CYFS#81]
**The purpose of the feature**
We know PeopleObject is very important, and a lots of content(data asset)'s owner would set to my PeopoeObject's ID. 
But some times, I feel that my PeopleObject's private key was leaked. If i create a new PeopleObject, I MUST move all old content's owner to new PeopleId. It's too difficult for me, it's even impossible

**Describe the solutions to the feature you'd like**
Like EOS Account or ETH Contract Account, I can use a tx to replace my PeopleObject's public key and donn't change the PeopleObject's ID?

**Additional context**
I know there be some risk: Someone take my private key and replace it , he can replace me totally ? The SBT theory can help us fix this long tearm risk?

**Comment by lurenpluto** [comment]
This is a rather complex issue, so that we can be continued in the following discussion:
#140
