### ISSUE TITLE
What happens when OOD disks run out?

### ISSUE THREAD

**Issue by waterflier** [buckyos/CYFS#84]
** General Question**
From the perspective of CYFS architecture, when OOD is used normally, any GET request in the zone will use OOD as the first jump cache. If the OOD disk is completely used up, will all the devices in the zone be unable to read data from the CYFS network? Does the OOD system reserve a system space for data reading?

**Comment by lurenpluto** [comment]
At present, the following OOD services will write data on the disk (the data is unified in the {cyfs} root directory)
+ ood-daemon
    For services updated
+ app-manager
    For app update && installation process, etc.
+ gateway
Currently cyfs-stack writes data on the disk, mainly including the following two parts
    - object cache, including database (sqlite) and object raw data (blob)
    - data cache, mainly used to manage chunks, for ndn data transmission without specifying a custom directory, etc.

Also all services have some additional debug information
+ log files, mainly used for current problem diagnosis and positioning, etc.

Therefore, when the disk where the cyfs root directory is located is completely run out, the following situations will occur
+ ood-daemon and app-manager cannot update and install services && app
+ cyfs-stack cannot add new objects and chunks
    But the existing get_object/get_chunk should not be affected, and the corresponding post_object should not be affected

**Comment by waterflier** [comment]
"cyfs-stack cannot add new objects and chunks" 
Is it means that I cann't get any new objects/chunks from CYFS Browser?  If CYFS Browser cann't get objects/chunks from OOD, would it get from Owner's OOD directly?

**Comment by lurenpluto** [comment]
> "cyfs-stack cannot add new objects and chunks" Is it means that I cann't get any new objects/chunks from CYFS Browser? If CYFS Browser cann't get objects/chunks from OOD, would it get from Owner's OOD directly?

When the disk is full, it is possible to read data normally, including chunk and object, just can not write new data, including put operations and some cache operations, so even if the OOD's disk is full, the other devices inside the zone can also be normal ge data from the OOD, if it is cross-zone to get object, the impact is that these object will fail to cache on the OOD

If CYFS Browser cann't get objects/chunks from OOD, only in the case that there is no such data on OOD then it will not be able to get, and there is nothing to do with disk full or not. In this case, if the get operation only knows the object-id, there is no way to know its owner, so there is no way to initiate a traceability query to the owner.
