### ISSUE TITLE
trans().publish_file not support config access

### ISSUE THREAD

**Issue by lizhihongTest** [buckyos/CYFS#86]
Using the trans().publish_file() interface does not support configuration file access, and the file object needs to be mounted on the root through the root_state interface before other devices can download the file. It is recommended to add permission configuration function to trans().publish_file() interface

**Comment by lurenpluto** [comment]
Add access param support for publish_file and build_file relate methods

4a547ca3df1feb91580ab17ed40cd23e3466f6ff
